### ISSUE TITLE
LOG INFO not displaying correctly in Chrome or IE

### ISSUE THREAD

**Issue by apuschak** [dalibo/pgbadger#172]
Hi,

The LOG INFO popup after pressing the "i" button at the top right displays past the window which does not scroll to the right to see the full popup.

![loginfo](https://cloud.githubusercontent.com/assets/8026978/3431297/490e4f6e-0069-11e4-8d99-fff1839bc4dc.PNG)

Resizing the window larger does fix this. However, resizing smaller does not and starting from full screen does not let you resize larger.

![loginforesized](https://cloud.githubusercontent.com/assets/8026978/3431360/d7d61542-0069-11e4-90b6-2a9b5d0f8756.PNG)

I'm using pgBadger version 5.1. and the latest Chrome. IE is up to date and is missing the text in the navigation, but I don't use IE often so I may be missing something there, however the popup issue is the same.

The popup does display correctly in up to date Firefox.

![loginfofirefox](https://cloud.githubusercontent.com/assets/8026978/3431501/321b104c-006b-11e4-8f41-dd3a632fa695.PNG)

Let me know if you need any more info!

**Comment by darold** [comment]
This seems to be fixed now, Firefox and chrome are both displaying the tooltip correctly.
