### ISSUE TITLE
client ip adresses are replaced by their DNS name - question

### ISSUE THREAD

**Issue by jirihlinka** [dalibo/pgbadger#205]
1) Thank you very much for implementing this functionality!
2) I have an issue with it:
 - in Queries > Queries by host, there are some host resolved and some not. When I run nslookup [IP], I'll get the FQDN and PTR exists for the IPs which are not replaced by FQDN. How does pgbadger resolve the FQDN from IP exactly? How can I simulate it to find out where is the problem?
 - Connections > Connections by host, I have all IPs (none of the IPs is replaced by its FQDN).
Is there a reason for this or is it a bug?

Thank you guys,
Jiri Hlinka

**Comment by darold** [comment]
Does $DNSLookupTimeout help to solve your issue?
