### ISSUE TITLE
Undefined subroutine &main::tempfile called at /usr/bin/pgbadger line 1168

### ISSUE THREAD

**Issue by forall** [dalibo/pgbadger#222]
Hi, 

I have CentOS 5.11 x64, perl5.8.8 and when I try /usr/bin/pgbadger -j 4 /var/lib/pgsql/postgresql-2015-02-04.log and get error: Undefined subroutine &main::tempfile called at /usr/bin/pgbadger line 1168.
pgBadger version 6.2 from yum repository, pgbadger from git works fine.

**Comment by darold** [comment]
Hi, maybe it's the same problem than with issue 67. Upgrade to Perl v5.8.9 might solve the issue.

Regards
