### ISSUE TITLE
Logging statements with log_min_duration does not maintaing sequence

### ISSUE THREAD

**Issue by grzeg1** [dalibo/pgbadger#223]
When statements are logged with log_min_duration_statement only, the sequence in logs is not maintained. Statement appears in log only after it's executed. That's why we log all statements and additionally duration for statements longer than 100ms. Duration then comes in a separate line after the statement has finished. Is there any chance pgBadger could support this kind of logging? If I were fluent in Perl I would have done it myself ;)

**Comment by grzeg1** [comment]
Great tool by the way - I forgot to mention ;)

**Comment by darold** [comment]
Hi,

Thanks for the encouragement and the feature request. After thinking a little about that it just takes me few time to add minimal support to log_duration + log_statement='all' into pgbadger. Please download latest code from github and give it a try.

Just use pgbadger as usual but by adding the --log-duration command line option. Let us know.

Regards,

**Comment by grzeg1** [comment]
You're quicker than lightning ;)
I just tried and it seems to do the job for the slow queries. But it skips all the others.
Could we assume e.g 1ms time for every query without duration info and still include them?
Also 1 tiny bug: histogram of query times y-axis should imho have 0 minimum. Now when all queries fall in the same segment, the chart seems to be empty.

**Comment by grzeg1** [comment]
Last one was easy. But anyway the bar shows at the left edge. So there's something else to fix.
```
diff --git a/pgbadger b/pgbadger
index 5ad1f14..3a8f8fd 100755
--- a/pgbadger
+++ b/pgbadger
@@ -10613,6 +10613,7 @@ sub flotr2_duration_histograph
            mode: "normal",
             title: "Number of queries",
            autoscaleMargin: 1,
+           min: 0,
            max: $max,
            tickFormatter: function(val){ return pretty_print_number(val,'') },
         },
```

**Comment by darold** [comment]
Applied in commit 7fcbf85

Could you post here the graph image as I will be able to understand what is still wrong?

**Comment by darold** [comment]
Hum, I don't understand what you mean by "But it skips all the others.", if you have log_duration enabled and log_statement set to all you should have all queries reported. Could you explain more?

**Comment by grzeg1** [comment]
with `--log-duration`
```
gg@krowa:/usr/src$ pgbadger/pgbadger  -j 8 --log-duration -p '%t %p ' psqlog
[========================>] Parsed 1813097 bytes of 1813097 (100.00%), queries: 13, events: 0
LOG: Ok, generating html report...
```
without `--log-duration`
```
gg@krowa:/usr/src$ pgbadger/pgbadger  -j 8  -p '%t %p ' psqlog
[========================>] Parsed 1813097 bytes of 1813097 (100.00%), queries: 6548, events: 0
LOG: Ok, generating html report...
```

**Comment by grzeg1** [comment]
Bar shows at the left margin. In JavaScript it is `var d1 = [ [1, 13]];` so Flot renders correctly, just data should have a different index.
![shutter_018](https://cloud.githubusercontent.com/assets/8179857/6169110/7a6e19b2-b2cb-11e4-830f-cae5f0e0360a.png)

**Comment by darold** [comment]
Could you send me your log at my private address gilles@darold.net ?

**Comment by grzeg1** [comment]
you've got mail ;)

**Comment by darold** [comment]
ok, thanks. I was able to fixed the histogram issue in last commit 39c42e0 but not the issue on query count. Your lof has just 2 queries and they all appear in the report. Could you send your full log?

**Comment by grzeg1** [comment]
I can send bigger log but please take one more look at what I sent as it's easier to count individual queries in such a small sample. I can even paste it here as it does not contain sensitive data:
```
2015-02-10 06:45:02 CET 13203 LOG:  statement: DEALLOCATE pdo_stmt_00000013
2015-02-10 06:45:02 CET 13203 LOG:  execute pdo_stmt_00000014: SELECT t_customer_field_values.id_customer AS _t_customer_field_values_id_customer, t_customer_field_values.id_customer_field AS _t_customer_field_values_id_customer_field, t_customer_field_values.value AS _t_customer_field_values_value, t_customer_field_values.id_customer_field_value AS _t_customer_field_values_id_customer_field_value FROM t_customer_field_values WHERE id_customer_field = $1 AND id_customer = $2
2015-02-10 06:45:02 CET 13203 DETAIL:  parameters: $1 = '30', $2 = '59082'
2015-02-10 06:45:02 CET 13203 LOG:  duration: 112.850 ms
2015-02-10 06:45:02 CET 13203 LOG:  statement: DEALLOCATE pdo_stmt_00000014
2015-02-10 06:45:02 CET 13203 LOG:  execute pdo_stmt_00000015: INSERT INTO t_customer_field_values (id_customer, id_customer_field, value) VALUES ($1, $2, $3)
2015-02-10 06:45:02 CET 13203 DETAIL:  parameters: $1 = '59082', $2 = '30', $3 = ''
2015-02-10 06:45:02 CET 13203 LOG:  statement: DEALLOCATE pdo_stmt_00000015
2015-02-10 06:45:02 CET 13203 LOG:  execute <unnamed>: SELECT CURRVAL($1)
2015-02-10 06:45:02 CET 13203 DETAIL:  parameters: $1 = 't_customer_field_values_id_customer_field_value_seq'
2015-02-10 06:45:02 CET 13203 LOG:  execute pdo_stmt_00000016: SELECT t_customer_fields.name AS _t_customer_fields_name, t_customer_fields.position AS _t_customer_fields_position, t_customer_fields.type AS _t_customer_fields_type, t_customer_fields.id_customer_field AS _t_customer_fields_id_customer_field FROM t_customer_fields WHERE id_customer_field IN ($1)
2015-02-10 06:45:02 CET 13203 DETAIL:  parameters: $1 = '30'
2015-02-10 06:45:02 CET 13203 LOG:  statement: DEALLOCATE pdo_stmt_00000016
```
As you can see it contains at least 3 different SELECT and 1 INSERT query. 

When I run pgbadger without the new option it shows `DEALLOCATE pdo_stmt_00; ` as number 1 of most frequent (N) queries. 
With the new option number 1 is `DEALLOCATE pdo_stmt_00 lue AS _t_customer_field_values_value, t_customer_field_values.id_customer_field_value AS _t_customer_field_values_id_customer_field_value FROM t_customer_field_values WHERE id_customer_field = '' AND id_customer = ''; ` which seems to be composition of 2 different queries.

Without the new option Most frequent queries (N) lists 5 rows, with the option only 2.

Without the new option overview counts 9 queries (5 unique), with option 2 queries (2 unique).

**Comment by darold** [comment]
Ok, a quick look made me thougth that the select queries was the same. I will investigate more with those line. Don't send the log, I will tell you.

**Comment by darold** [comment]
Well, this is not possible here to associate durations to queries. In your log example if the duration can be associated to the first SELECT query. The next queries doesn't have a duration log entry following immediatly the query log. That would not be a problem if the pid was different but here this is not the case.

**Comment by grzeg1** [comment]
In this kind of log:
for a given PID:
- if there is a new statement - duration is less then defined threshold (e.g less than 100ms)
- if there is a `duration` line - duration is what is specified in the log line
So I thought the formula can be like:
- set duration for a query to 1ms, save query for this PID for later processing
- if the next line for the same same PID is another query - update pointer
- if the next line for the same PID is `duration` - update  duration
- process saved query
This is how my PHP script for listing long queries worked. But it can't do anything else.

**Comment by grzeg1** [comment]
Unfortunately one of the last changes broke counting of queries/sec. Charts show always 0. Running without `--log-duration` option. The version before `--log-duration` was introduced is OK.

**Comment by darold** [comment]
Last commit 5a62259 might fix that issue.
