### ISSUE TITLE
HTML report is too large

### ISSUE THREAD

**Issue by laurenz** [dalibo/pgbadger#225]
We created a report like this:

    pgbadger --begin '2015-02-26 14:00:00' --end '2015-02-26 15:00:00' --outfile gisalast.html --dbname gisalast --title 'GISA-LASTEST' /POSTGRES/export/GISA-2015-02-26.csv
    [======================>  ] Parsed 45771244066 bytes of 48892192514 (93.62%), queries: 3290554, events: 30
    LOG: Ok, generating html report...

The resulting HTML file is about 325 MB large and crashes our Mozilla Firefox.
What could be the problem?

**Comment by darold** [comment]
Perhaps some very big queries or some memory dump garbage. You might want to use:
    --maxlength 2048
to truncate queries at a reasonable size. Let's see if you found garbage in the report.

**Comment by laurenz** [comment]
Thanks, that helped!
There were indeed a few extremely long queries at fault.
