### ISSUE TITLE
 can't read file LAST_PARSED.tmp

### ISSUE THREAD

**Issue by gonxalo2000** [dalibo/pgbadger#226]
Yesterday i download the last version of pbbadger. Then make a bash file in a remote server with apache, here's the code:
------------------------------
#!/bin/bash

SERVER=postgres
DIR_LOG_SERVER=/var/log/pg_log

ssh ${SERVER} 'cat ' "${DIR_LOG_SERVER}"'/*.log' | /usr/bin/pgbadger -I -O /var/www/pgBadger6 -
------------------------------
I run it onece and i get the reports and all was ok.
I run a second time and i get ...

WARNING: can't read file /var/www/pgBadger6/LAST_PARSED.tmp, No such file or directory
HINT: maybe there's no new entries in your log since last run.
LOG: Ok, generating global index to access incremental reports...

This is a production database and the logs gets a lot of entries between runs.
I look out for the file and it does not exists, but It exists: /var/www/pgBadger6/LAST_PARSED
What i'm doing wrong!?
Tks a lot.

**Comment by darold** [comment]
Usually this is just a warning, it means that there's no new log entries from the last run. But here I thing this is the use of stdin that generate the problem. pgBadger embeded the remote log parsing feature, could you try with it and see if that solves your issue?

Extracted from the documentation:

    -r | --remote-host ip  : set the host where to execute the cat command on
			     remote logfile to parse localy the file.

pgBadger is able to parse a remote log file using a passwordless ssh connection.
Use the -r or --remote-host to set the host ip address or hostname. There's also
some additional options to fully control the ssh connection.

    --ssh-program ssh        path to the ssh program to use. Default: ssh.
    --ssh-user username      connection login name. Default to running user.
    --ssh-identity file      path to the identity file to use.
    --ssh-timeout second     timeout to ssh connection failure. Default 10 secs.
    --ssh-options  options   list of -o options to use for the ssh connection.
			     Options always used:
                                 -o ConnectTimeout=$ssh_timeout
                                 -o PreferredAuthentications=hostbased,publickey

**Comment by gonxalo2000** [comment]
Ok, but what's the invocactio!?

I use: 
/usr/bin/pgbadger -I -r ${SERVER} ${DIR_LOG_SERVER}/*.log -O /var/www/pg6
i get the ssh message from the server bu i also get: 
ls: cannot access /var/log/pg_log/postgresql-2015-02-24_145102.log: No such file or directory
for each file and a final:
FATAL: you must give a log file format (-f or --format) when using remote connection.

Tks again.

**Comment by darold** [comment]
This is the right command, you just have to set the log format because pgbadger do not autodetect it   in remote mode. If you are using stderr as log_destination add the following to your command:

    -f stderr

This will solves the last message but for the first error you need to use a user for your ssh connection that has priviledge to read the log file. Here that's doesn't seem the case. You can list files but not read them I guess.

**Comment by gonxalo2000** [comment]
Great. Now it works, 
/usr/bin/pgbadger -f stderr -I /var/log/pg_log/postgresql*.log -O /var/www/pgBadger6 -r postgresqlprod

but...
I have this logs in this directory...
postgresql-2015-02-15_000000.log
postgresql-2015-02-16_000000.log
postgresql-2015-02-17_000000.log
postgresql-2015-02-18_000000.log
postgresql-2015-02-19_000000.log
postgresql-2015-02-20_000000.log
postgresql-2015-02-21_000000.log
postgresql-2015-02-22_000000.log
postgresql-2015-02-23_000000.log
postgresql-2015-02-24_000000.log
postgresql-2015-02-25_000000.log
postgresql-2015-02-26_000000.log
postgresql-2015-02-27_000000.log

The command runs ...
I get....
ls: cannot access /var/log/pg_log/postgresql-2014-12-17_000000.log: No such file or directory
ls: cannot access /var/log/pg_log/postgresql-2014-12-18_000000.log: No such file or directory
etc...


and finally does the job with 
LOG: Ok, generating HTML daily report into /var/www/pgBadger6/2015/02/25/...
LOG: Ok, generating HTML daily report into /var/www/pgBadger6/2015/02/26/...
LOG: Ok, generating HTML daily report into /var/www/pgBadger6/2015/02/27/...
        LOG: Ok, generating HTML weekly report into /var/www/pgBadger6/2015/week-09/...
LOG: Ok, generating global index to access incremental reports...


It does not process 24, 23, etc...

if a launch the script again, i get the same errors. and it process this
[========================>] Parsed 138252504 bytes of 97007904 (142.52%), queries: 0, events: 0
[========================>] Parsed 137247687 bytes of 96003087 (142.96%), queries: 0, events: 0
[========================>] Parsed 82689086 bytes of 41401137 (199.73%), queries: 23, events: 0
LOG: Ok, generating HTML daily report into /var/www/pgBadger6/2015/02/27/...
LOG: Ok, generating HTML weekly report into /var/www/pgBadger6/2015/week-09/...
LOG: Ok, generating global index to access incremental reports...

Why? I have a banner in the server... when i do ssh manually i get:
######################################
#                                    #
#             XXXXXXXXXXX      #
######################################
and when pgbadger is runing i see this message for every connection it opens.

Tks!

**Comment by darold** [comment]
About your banner, you might see your ssh_config file to disable it for certain login, pgBadger can host help you on this problem.

Could you post here the result of the following command line:

    ssh postgresqlprod ls -la /var/log/pg_log/postgresql*.log

**Comment by gonxalo2000** [comment]
This:

 -rw-rw---- 1 postgres postgres  95730709 Feb 16 00:00 /var/log/pg_log/postgresql-2015-02-15_000000.log
-rw-rw---- 1 postgres postgres  95641799 Feb 16 23:59 /var/log/pg_log/postgresql-2015-02-16_000000.log
-rw-rw---- 1 postgres postgres  95396382 Feb 17 23:59 /var/log/pg_log/postgresql-2015-02-17_000000.log
-rw-rw---- 1 postgres postgres 107018434 Feb 19 00:00 /var/log/pg_log/postgresql-2015-02-18_000000.log
-rw-rw---- 1 postgres postgres 156467056 Feb 19 23:59 /var/log/pg_log/postgresql-2015-02-19_000000.log
-rw-rw---- 1 postgres postgres 143184944 Feb 21 00:00 /var/log/pg_log/postgresql-2015-02-20_000000.log
-rw-rw---- 1 postgres postgres 160360879 Feb 22 00:00 /var/log/pg_log/postgresql-2015-02-21_000000.log
-rw-rw---- 1 postgres postgres  95407981 Feb 23 00:00 /var/log/pg_log/postgresql-2015-02-22_000000.log
-rw-rw---- 1 postgres postgres 100181792 Feb 24 00:00 /var/log/pg_log/postgresql-2015-02-23_000000.log
-rw-rw---- 1 postgres postgres  95888374 Feb 25 00:00 /var/log/pg_log/postgresql-2015-02-24_000000.log
-rw-rw---- 1 postgres postgres  97007904 Feb 25 23:59 /var/log/pg_log/postgresql-2015-02-25_000000.log
-rw-rw---- 1 postgres postgres  96003087 Feb 27 00:00 /var/log/pg_log/postgresql-2015-02-26_000000.log
-rw-rw---- 1 postgres postgres  55154510 Feb 27 13:51 /var/log/pg_log/postgresql-2015-02-27_000000.log

also the dir has:

"ssh postgresqlprod "ls -la /var/log/pg_log/"

-rw-rw----  1 postgres postgres  41758124 Feb  2 00:31 logs_2015-01-26.tar
-rw-rw----  1 postgres postgres  36113641 Feb  9 00:31 logs_2015-02-02.tar
-rw-rw----  1 postgres postgres  38966381 Feb 16 00:30 logs_2015-02-09.tar
-rw-rw----  1 postgres postgres  43869825 Feb 23 00:30 logs_2015-02-16.tar
-rw-rw----  1 postgres postgres  95730709 Feb 16 00:00 postgresql-2015-02-15_000000.log
-rw-rw----  1 postgres postgres  95641799 Feb 16 23:59 postgresql-2015-02-16_000000.log
-rw-rw----  1 postgres postgres  95396382 Feb 17 23:59 postgresql-2015-02-17_000000.log
-rw-rw----  1 postgres postgres 107018434 Feb 19 00:00 postgresql-2015-02-18_000000.log
-rw-rw----  1 postgres postgres 156467056 Feb 19 23:59 postgresql-2015-02-19_000000.log
-rw-rw----  1 postgres postgres 143184944 Feb 21 00:00 postgresql-2015-02-20_000000.log
-rw-rw----  1 postgres postgres 160360879 Feb 22 00:00 postgresql-2015-02-21_000000.log
-rw-rw----  1 postgres postgres  95407981 Feb 23 00:00 postgresql-2015-02-22_000000.log
-rw-rw----  1 postgres postgres 100181792 Feb 24 00:00 postgresql-2015-02-23_000000.log
-rw-rw----  1 postgres postgres  95888374 Feb 25 00:00 postgresql-2015-02-24_000000.log
-rw-rw----  1 postgres postgres  97007904 Feb 25 23:59 postgresql-2015-02-25_000000.log
-rw-rw----  1 postgres postgres  96003087 Feb 27 00:00 postgresql-2015-02-26_000000.log
-rw-rw----  1 postgres postgres  55934279 Feb 27 14:02 postgresql-2015-02-27_000000.log

can be the weekly tar of log making noice?

tks.

**Comment by darold** [comment]
Hi,

You need to enclose the logfile parameter between  double quote otherwise your parameter will be automatically replaced by the files on your localhost at command line:

    /usr/bin/pgbadger -f stderr -I -O /var/www/pgBadger6 -r postgresqlprod "/var/log/pg_log/postgresql*.log"

With the command on the previous note you can see that log file name and file size are taken locally.

**Comment by gonxalo2000** [comment]
You're righT! It works fine now.
Tks a log again.!
