### ISSUE TITLE
Could we get option to read list of logfiles from a file/stdin?

### ISSUE THREAD

**Issue by depesz** [dalibo/pgbadger#228]
I have a case where I put report of literally thousands of logfiles into single html.

Passing them all in command line is complicated, and I'm nor sure if it will be possible if the list will grow.

Could we get an option to read list of logfiles from a file, instead of specifying them on stdin?

I know I can join multiple logfiles into .bin, and then make analysis of just small number of these .bin files, but I already did it, and still have many files. I would very much prefer to avoid joining these even further.

**Comment by darold** [comment]
Are you sure you need such a feature because you can use shell regexp in command line. For example if we supposed that you are collecting log files from several servers and stores them in separate directories, you can proceed something as follow:

    pgbadger ... /var/log/postgresql/hosts/*/postgresq-9.[23].log*

Or is this something  that you can not solves like that? If regex does not solve your issue, does the following can not help?

    pgbadger ... `cat list_pg_logfile.txt`

Regards,

**Comment by depesz** [comment]
I am generating the list in script. It's just that I'm afraid of hitting system limit of number of arguments.

**Comment by darold** [comment]
ok, I will work on that asap

**Comment by depesz** [comment]
Thanks a lot.

**Comment by darold** [comment]
Last commit 3dc9a2f should add this feature. Download and use pgbadger as follow:

    pgbagder .... -L logfile_list.txt

where logfile_list.txt must contain a list of log file, one per line. Log files can also be passed using both logfile list and command line arguments:

    pgbagder .... -L logfile_list.txt /var/log/postgresql-9.3.log*

Let me know.

**Comment by depesz** [comment]
Looks great. will test and let you know, but most likely tomorrow, not today.

**Comment by depesz** [comment]
Works. Thanks a lot.
