### ISSUE TITLE
Mean number of relations per query

### ISSUE THREAD

**Issue by rodo** [dalibo/pgbadger#230]
Hi,

What do you think to report the mean number of relations per queries ? I think it could be a good indicator of the complexity of the queries. It could help to explain some long queries due to locks on one of the relation involve in queries, or not :)

Regards

**Comment by darold** [comment]
Hi,

Yes that would be a good information to display, unfortunatelly it is difficult to obtain with regex. For simple queries this is easy, but with queries using multiple subqueries this is quite impossible to do. As every one is able to count the number of relation on simple query there is not interest to do that for the moment, at least until we have a SQL lexer/parser in pgbadger.

Thanks for the suggestion.

**Comment by rodo** [comment]
Thanks for the answer, please feel free to close my issue apart if you are currently coding the lexer/parser that pgbadgers misses :)

**Comment by darold** [comment]
It may be quicker to develop a PostgreSQL extension that output this information as query detail in log file. pgBadger will parse it easily, fill free to reopen the issue when it will be completed :-)
