### ISSUE TITLE
Graphic artifacts when hovering over graphs with mouse

### ISSUE THREAD

**Issue by brianjsw** [dalibo/pgbadger#231]
I didn't notice this issue reported anywhere, but I noticed that when using any browser (Firefox, Safari, Chrome) on OS X, or when using Chrome under Windows, that the graphs display graphical artifacts as you hover over them.  The more you hover back and forth, the worse it gets, until the entire graph appears to have a solid gray background (from the gray veritical-line pointer not unpainting itself as you move the mouse).   It appears to be related to the vertical line that "trails" the mouse pointer to show where you are in the graph.  Not a show-stopper, just a nice-to-fix I suppose.

**Comment by darold** [comment]
I've not seen that problem for months, what version of pgbadger and firefox are you using?

**Comment by bjs987** [comment]
I'm seeing the issue while running pgbadger 6.2 in the following configurations:

OS X:  (All browsers are affected)-> Safari 8.0.4 (10600.4.10.7),  Firefox 36.0.4, and Chrome 41.0.2272.101 (64-bit)

Windows:  Only Google Chrome is affected.  Version:"41.0.2272.101 m"

**Comment by joemontibello** [comment]
Me too, seeing the same problem here. 
OS X: 10.10.2
pgbadger 6.2
Firefox 36.0.4
Safari 8.0.4
For extra fun, I ctrl+clicked one of the images with artifacts all over it and chose "view image." The image I got didn't have the chart in it, but it did have the grid of artifacts!

Anyway, thanks for a great tool!

**Comment by darold** [comment]
I have updated flotr2.js to latest development code, please download pgbadger latest development code and give it a try.

**Comment by joemontibello** [comment]
I'm still seeing the issue. The output file that I'm looking at is at:
http://catalog-lib.dartmouth.edu/screens/out.html

**Comment by darold** [comment]
Ok, with my Firefox 36.0.4 on Linux I'm not able to reproduce the issue even with your link.

**Comment by darold** [comment]
This is fix with commit 4c5dee2 which replace flotr2 javascript library with jqplot. This was the main reason of the library change.
