### ISSUE TITLE
"Applications involved"

### ISSUE THREAD

**Issue by kogitant** [dalibo/pgbadger#235]
For example the "Most frequent queries (N)" feature provides a button to show which users have been involved in executing the queries. Would it be possible to have a similar button for "applications involved"?

**Comment by darold** [comment]
Yes that's possible, I will try to add this before the next major release. Thanks for the feature request.

**Comment by darold** [comment]
This feature is available in current development code with commit 781c0c8.

Regards

**Comment by kogitant** [comment]
Excellent, thank you veri much.
