### ISSUE TITLE
Empty info, though "519 log entries parsed"

### ISSUE THREAD

**Issue by scythargon** [dalibo/pgbadger#236]
![screen]
(http://storage2.static.itmages.com/i/15/0507/h_1431011065_7511014_4fb589a09a.png)
Hello! Thank you for your awesome package! Though I fail to use it, it looks promising:)
Just erased my log file, restarted postgres server, runned my application a bit, executed `./pgbadger /var/log/postgresql/postgresql-9.4-main.log` and got this empty log visualization.
Postgis and hstore extensions are installed in database, log config is 
```
# - What to Log -

#debug_print_parse = off
#debug_print_rewritten = off
#debug_print_plan = off
#debug_pretty_print = on
#log_checkpoints = off
log_connections = on
log_disconnections = on
log_duration = on
#log_error_verbosity = default          # terse, default, or verbose messages
#log_hostname = off
log_line_prefix = '%t [%p-%l] %q%u@%d '                 # special values:
                                        #   %a = application name
                                        #   %u = user name
                                        #   %d = database name
                                        #   %r = remote host and port
                                        #   %h = remote host
                                        #   %p = process ID
                                        #   %t = timestamp without milliseconds
                                        #   %m = timestamp with milliseconds
                                        #   %i = command tag
                                        #   %e = SQL state
                                        #   %c = session ID
                                        #   %l = session line number
                                        #   %s = session start timestamp
                                        #   %v = virtual transaction ID
                                        #   %x = transaction ID (0 if none)
                                        #   %q = stop here in non-session
                                        #        processes
                                        #   %% = '%'
                                        # e.g. '<%u%%%d> '
#log_lock_waits = off                   # log lock waits >= deadlock_timeout
log_statement = 'all'                   # none, ddl, mod, all
#log_temp_files = -1                    # log temporary files equal or larger
                                        # than the specified size in kilobytes;
                                        # -1 disables, 0 logs all temp files
log_timezone = 'localtime'
```

Thank you!

**Comment by scythargon** [comment]
Checked in chrome and firefox.

**Comment by darold** [comment]
Hi,

If you don't use the default prefix used by pgbadger, pgbadger will not look at you configuration file to know which prefix you use so running pgbadger as follow should be better:

    ./pgbadger -p '%t [%p-%l] %q%u@%d ' /var/log/postgresql/postgresql-9.4-main.log

Also having log_min_duration_statement >= 0 might help to fill the log.

Regards,

**Comment by scythargon** [comment]
Yay! works!
Now why there is no info in "Slowest individual queries" and "Time consuming queries" paragraphs?
![image]
(http://storage3.static.itmages.com/i/15/0507/h_1431012193_7889404_32bb5e5405.png)

**Comment by darold** [comment]
quote: "Also having log_min_duration_statement >= 0 might help to fill the log."

**Comment by scythargon** [comment]
Right, sorry, tried that before writing my previous comment, got:
`Error: Invalid line 395 in /etc/postgresql/9.4/main/postgresql.conf: »log_min_duration_statement > 0	# -1 is disabled, 0 logs all statements«
 * No PostgreSQL clusters exist; see "man pg_createcluster"`

**Comment by scythargon** [comment]
Nevermind, worked with just "=", failed with ">=" and ">", trying...

**Comment by scythargon** [comment]
Naah, still empty paragraphs

**Comment by scythargon** [comment]
Excuse me my impatience, really can't figure out what does it need for these to most important parts of the info:( even pasted whole log here, may be you can take a look at it http://pastebin.com/h3ESp9XY

**Comment by darold** [comment]
Please take time to read the documentation before asking help. In your case I especially recommend you to read chapter " log_min_duration_statement, log_duration and log_statement", otherwise you and me are loosing our time.

Regards,
