### ISSUE TITLE
Report request: Sessions per application name

### ISSUE THREAD

**Issue by keithf4** [dalibo/pgbadger#239]
Any chance you could add a new application name report to the sessions charts/tables? The new `Queries by application` is nice, but it would be more useful to get overall session metrics. We're trying to narrow down those services that still don't have an application name set and this would help tremendously. Thanks!

**Comment by darold** [comment]
Hi,

I guess last commit 8969d1c might adds what you are looking for, a new Sessions per application report. Let us know.

Regards,

**Comment by keithf4** [comment]
Works! Thanks.
