### ISSUE TITLE
Error gettin report

### ISSUE THREAD

**Issue by gonxalo2000** [dalibo/pgbadger#240]
Hi, i have a script that preforms incremental report.
Today i found that i cant acces the site. page si blank.
Files in root site directory shows:

Jun  1 04:00 index.html
Jun  1 11:08 LAST_PARSED

If i run the script again, LAST_PARSED changes whit last entry:
2015-06-01 11:16:05    
But i get the error
[========================>] Parsed 86348794 bytes of 43190114 (199.93%), queries: 8, events: 0
Magic number checking on storable file failed at ../../lib/Storable.pm (autosplit into ../../lib/auto/Storable/fd_retrieve.al) line 398, at /usr/bin/pgbadger6 line 8029

in log files....

Tks!

**Comment by gonxalo2000** [comment]
One more thig. If a go into a reporte... .../2015/05/21/index.html it's ok. 
The main page is not loading...

**Comment by darold** [comment]
Hi,

Have you upgraded Perl or the Storable perl Module ?

Regards,

**Comment by gonxalo2000** [comment]
I'm not linux administrator, but i think i dont't
Mi version of perl is
This is perl, v5.10.1 (*) built for x86_64-linux-thread-multi

and 

pgBadger version 6.2

**Comment by darold** [comment]
Sorry, I've totally forgotten this issue, do you still have the problem? If not please drop a note about the solution used.

**Comment by gonxalo2000** [comment]
Hi, the incremental script keep running and now, my index page is fine.

Tks!
