### ISSUE TITLE
No information in Screen top Queries

### ISSUE THREAD

**Issue by lours1** [dalibo/pgbadger#243]
when i parse the log file with this command (v7 and v7.1)
perl D:\log\GHDC\postgresql-2015-07-14_000001\perl\pgbadger D:\log\GHDC\postgresql-2015-07-14_000001\postgresql-2015-07-14_000001.log  -o D:/log/GHDC/postgresql-2015-07-14_000001/results/PGB_2015-07-14_.html --exclude-query "^(VACUUM|COMMIT|ANALYSE|COPY)" --dbuser arthur -m 6000

The top queries return no information, but if i run it with file generated yesterday (there is no change in config postgres between two log file) i got data in this section

I can provide log file for debug, but i just don't know how to send you :)

**Comment by darold** [comment]
Hi,

Well if it is small enough (I mean <= 5MB)  after compression you can send it directly to my private address gilles@darold.net, otherwise you can use any file upload/download site.

Best regards,

**Comment by darold** [comment]
Do you have some transformation on your log? There should be two white spaces after the duration field and there's just one in you log:

     LOG: duration: 356.176 ms parse <unnamed>: SELECT * FROM 

The two white space should be after ms and there's just one. Commit fc4432d should allow you to parse this log.

**Comment by lours1** [comment]
Hi darold,
no i don't do any transform of log,
don"'t understand why the log don"t work anymore, so thank you for you help

**Comment by darold** [comment]
What are your version of PostgreSQL and Windows OS ?

**Comment by lours1** [comment]
You patch are working thank you 

you wan check our config for log with this link http://pastebin.com/cm9tng29
and we use postgres 9.0.12 on centos 5.5

**Comment by darold** [comment]
Ok, maybe the double white space have been removed during the transfert.
