### ISSUE TITLE
Possible Parsing Problem

### ISSUE THREAD

**Issue by mikealbert** [dalibo/pgbadger#244]
Hi,

I'm running into an issue with parsing a postgres logfile with pgbadger.  Just wanted to confirm it wasn't due to the syntax I'm using.  Here's the task I have set to run via cron:
```
/usr/bin/pgbadger --retention 4 --exclude-query="^(COPY|COMMIT|DEALLOCATE|BEGIN)" --exclude-user newrelic -I -q `find /var/lib/pgsql/9.4/data/pg_log/ -name postgresql-20*.log` -O /var/www/html/
```

This job is set to run every 5 minutes.  It works for awhile, but eventually the year dir (2015) under /var/www/html gets created as just "5" and the LAST_PARSED file appears to show an incomplete log entry.  Here's an example:

```
5-07-09 16:46:05	953079	5-07-09 16:46:05 EDT [14542]: [2-1] user=foo,db=foo_staging LOG:  connection authorized: user=foo database=foo_staging
```

**Comment by mikealbert** [comment]
Just to provide a bit more detail.  When the cronjob first executes, the directory structure under /var/www/html looks like this
```
drwxr-xr-x 5 root root   4096 Jul 17 14:50 2015
-rw-r--r-- 1 root root 501507 Jul 17 15:20 index.html
-rw-r--r-- 1 root root    199 Jul 17 15:20 LAST_PARSED
```
However, after a handful of executions the structure changes to this
```
drwxr-xr-x 3 root root   4096 Jul 17 15:25 5
-rw-r--r-- 1 root root 499855 Jul 17 15:30 index.html
-rw-r--r-- 1 root root    163 Jul 17 15:25 LAST_PARSED
```
Contents of LAST_PARSED show a truncated log line similar to what I pasted above.

Thanks in advance for the help!

**Comment by darold** [comment]
Please upgrade to pgBadger 7.1, commit e942102 should have fixed this issue. If this is not case please let me know.

Best regards/

**Comment by mikealbert** [comment]
Just double checked, and I'm already running pgBadger 7.1 on the host which is having this issue.

**Comment by darold** [comment]
After several months running the same call to pgBadger in a cron job I'm still not able to reproduce the issue. Does the problem occurs again at your side?
