### ISSUE TITLE
update ubuntu repo to include precise 12.04

### ISSUE THREAD

**Issue by oppianmatt** [dalibo/pgbadger#245]
https://launchpad.net/pgbadger doesn't have precise 12.04 lts

could we please have it?

**Comment by darold** [comment]
Hi,

Unfortunately the Debian packager responsible of the pgbadger package is not able to provide an up to date package, this is the same for Ubuntu. It is still version 3.3 and we are now in version 7.1, this is just a return in the past over 15 releases and more than 2 years.

Please do not use the Debian package for pgbadger, apparently the maintainer is not able to follow the community and will probably not do the necessary work in the future even if pgbadger has no dependency and just consist on a single standalone Perl script. There's certainly some logical reasons but I'm not informed of that. If you want you can add an other message to the Debian bug report at https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=785216 to hope someone can solve this problem.

The pgbadger latest release can always be found here : https://github.com/dalibo/pgbadger/releases

To install it just proceed as  follow:

    tar xzf pgbadger-7.1.tar.gz
    cd pgbadger-7.1/
    perl Makefile.PL
    make
    sudo make install

It will just copy the pgbadger script into /usr/local/bin/ which mean that you can also proceed as follow:

    cd pgbadger-7.1/
    sudo cp pgbadger /usr/local/bin/

Best regards,

**Comment by darold** [comment]
Debian repositories have been updated.
