### ISSUE TITLE
Pgbadger always parse 0 queries out of my pg log file

### ISSUE THREAD

**Issue by RealHacker** [dalibo/pgbadger#247]
My pg log is like this:

2015-07-28 10:43:58 CST LOG:  duration: 118.843 ms  statement: SELECT (1) AS "a" FROM "django_session" WHERE "django_session"."session_key" = '7afdb007f8a0f669c3468f2358ce8a558'  LIMIT 1
2015-07-28 10:43:58 CST LOG:  duration: 131.048 ms  statement: SELECT (1) AS "a" FROM "cart_order" WHERE ("cart_order"."submitted_at" IS NOT NULL AND "cart_order"."customer_phone" = '15062412065'  AND NOT ("cart_order"."_status" IN (1100, 200))) LIMIT 1
2015-07-28 10:43:58 CST LOG:  duration: 117.445 ms  statement: SELECT "api_deviceinfo"."id", "api_deviceinfo"."platform", "api_deviceinfo"."mac_address", "api_deviceinfo"."device_id", "api_deviceinfo"."last_login", "api_deviceinfo"."date_joined", "api_deviceinfo"."login_count" FROM "api_deviceinfo" WHERE ("api_deviceinfo"."platform" = 2  AND "api_deviceinfo"."device_id" = '40de9c943e2329'  AND "api_deviceinfo"."mac_address" = '8623024749319' )

But no matter how I adjust the command line options, pgbadger always returns an empty report.

pgbadger --prefix="%t CST LOG:" --log-duration -v -S newpostgresql-2015-07-28_1043.log 
pgbadger --prefix="%t CST LOG:  duration: %h ms  " -v -S newpostgresql-2015-07-28_1043.log 
pgbadger --prefix="%t CST LOG:  duration: %h ms  " --log-duration -v -S newpostgresql-2015-07-28_1043.log 
pgbadger --prefix="%t CST LOG:  duration: %p ms " --log-duration -v -S newpostgresql-2015-07-28_1043.log 
 
DEBUG: Autodetected log format 'stderr' from newpostgresql-2015-07-28_1043-newnew.log
DEBUG: Output 'html' reports will be written to out.html
DEBUG: Starting to parse log file: newpostgresql-2015-07-28_1043-newnew.log
DEBUG: Starting reading file newpostgresql-2015-07-28_1043-newnew.log...
DEBUG: Start parsing at offset 0 of file newpostgresql-2015-07-28_1043-newnew.log to 105043211
[========================>] Parsed 105043211 bytes of 105043211 (100.00%), queries: 0, events: 0
DEBUG: the log statistics gathering took: 0 wallclock secs ( 0.26 usr +  0.03 sys =  0.29 CPU)
LOG: Ok, generating html report...
DEBUG: building reports took:  0 wallclock secs ( 0.00 usr +  0.00 sys =  0.00 CPU)
DEBUG: the total execution time took:  0 wallclock secs ( 0.26 usr +  0.03 sys =  0.29 CPU)

What is happening?

**Comment by darold** [comment]
Hi,

Please read the documentation especially the part talking about postgresql.conf log_line_prefix.

Regards,

**Comment by RealHacker** [comment]
I understand log_line_prefix, in the postgresql.conf, it is set as "%t". But it doesn't work when I use --prefix="%t" for pgbadger. Any suggestions?

**Comment by RealHacker** [comment]
After adding an extra space after prefix="%t ", it miraculously works.

**Comment by pcav** [comment]
I seem to have the same issue, but adding a space does not solve it:

log_line_prefix = '%t  [%p]: [%l-1] user=%u,db=%d '

pgbadger /var/log/pgsql -o /var/www/html/pgbadger.html
[========================>] Parsed 206970 bytes of 206970 (100.00%), queries: 0, events: 0
LOG: Ok, generating html report...

The same string used to work in my previous installations.
Debian Jessie, with pgbager installed from the sid package (7.1-0.1).
Thanks for any hint.

**Comment by pcav** [comment]
Queries logged seem correct, e.g.:

Sep 30 16:40:55 sit postgres[9547]: [45-1] 2015-09-30 16:40:55 CEST  [9547]: [43-1] user=pcav,db=corso LOG:  durata: 1.470 ms  istruzione: SELECT count(*) FROM pg_stats WHERE schemaname='michele_ribecai' AND tablename='CBVM' AND attname='geom'

**Comment by darold** [comment]
Glad to see here that the old pgbadger package have been erased with version 7.1. All my recognition to The Duck,  Marc Dequenes from duckcorp.org.

The minor problem here is that you are logging to syslog, in this case you don't have to repeat the syslog prefix in the log_line_prefix. Please set the following:

    log_line_prefix = 'user=%u,db=%d '

or log to stderr. But it could works like this too, pgBadger is able to deal with that provided that the --prefix is right defined like here.

But the main problem is that your log are in italian. Our badger only read ANSI C messages, so your must set the following in your postgresql.conf:

    lc_message = 'C'

(en_US works too).

There's no work to translate log file and reports.

Regards,

**Comment by pcav** [comment]
My mistake: 
lc_messages = 'C'
instead of
lc_message = 'C'

**Comment by pcav** [comment]
I had it, but also the orginal locale. My mistake, sorry for the noise.

**Comment by pablo** [comment]
Ciao @pcav 
The problem is that you're logging in ITALIAN. You need to log in 'C' locale as stated in documentation:

    Of course your log messages should be in English without locale support:

            lc_messages='C'

===

**Comment by pcav** [comment]
Gracias @pablo for clarifying.
