### ISSUE TITLE
host/client is always unknown - issue or missconfig?

### ISSUE THREAD

**Issue by e-ruiz** [dalibo/pgbadger#249]
Hi guys!

Looking on PgBadger reports / Queries / Queries by host it always shows only "unkown" host.

All query reports are work very well, except "by hosts".

I already read readme file and tried many configs, but without results. I'm not sure if it is a bug or miss config.

PgBadger 7.1 and Postgres 9.4.4

Log sample:
```text
2015-08-12 16:17:45 BRT [63794]: [1-1] db=[unknown],user=[unknown],app=[unknown],host= LOG:  connection received: host=192.168.100.1 port=55134
2015-08-12 16:17:45 BRT [63794]: [2-1] db=mydb,user=webtest,app=[unknown],host=192.168.100.1 LOG:  connection authorized: user=webtest database=mydb
2015-08-12 16:17:46 BRT [63794]: [3-1] db=mydb,user=webtest,app=[unknown],host=192.168.100.1 LOG:  duration: 147.991 ms  statement: SELECT my_column FROM my_table WHERE last_column = 1234 ORDER BY first_column DESC LIMIT 1
```

**postgres.conf** double checked:
```text
log_line_prefix = '%t [%p]: [%l-1] db=%d,user=%u,app=%a,client=%h '
log_checkpoints = on
log_connections = on
log_disconnections = on
log_lock_waits = on
log_temp_files = 0
log_autovacuum_min_duration = 0
```

**PgBadger call:**
```text
pgbadger -j 8 -X -I -f stderr -q /var/log/postgresql94/postgresql-9.4-main.log -O /var/www/pgreports/
```

**And (after delete everything):**
```text
pgbadger -j 8 -X -I -q /var/log/postgresql94/postgresql-9.4-main.log -O /var/www/pgreports/
```

Thank you very much.

**Comment by darold** [comment]
It seems that your real log_line_prefix is:

    '%t [%p]: [%l-1] db=%d,user=%u,app=%a,host=%h '

so if you use:

    -p '%t [%p]: [%l-1] db=%d,user=%u,app=%a,host=%h '

it might works. If you don't want to use a command line prefix and that your log_line_prefix really use client instead of host, perhaps you have to reload your configuration file.

Regards

**Comment by e-ruiz** [comment]
Hello @darold , thanks a lot.

Please, take a look. With this scenario, does not work:
```text
user@postgres01# nano /pgsql/9.4/data/postgresql.conf
## log_line_prefix = '%t [%p]: [%l-1] db=%d,user=%u,app=%a,client=%h '

user@postgres01# service postgres restart
user@postgres01# tail -f /var/log/postgresql/postgresql.log 
2015-08-13 11:26:59 BRT [47439]: [1-1] db=[unknown],user=[unknown],app=[unknown],client= LOG:  connection received: host=192.168.100.10 port=49100
2015-08-13 11:26:59 BRT [47439]: [2-1] db=mydb,user=webtest,app=[unknown],client=192.168.100.10 LOG:  connection authorized: user=webtest database=mydb
^C

user@postgres01# pgbadger -j 8 -X -I -f stderr -q /var/log/postgresql/postgresql.log -O /var/www/pgreports/
```

Same scenario with command line prefix works fine.
```text
pgbadger -p '%t [%p]: [%l-1] db=%d,user=%u,app=%a,client=%h ' -j 8 -X -I -f stderr -q /var/log/postgresql94/postgresql-9.4-main-2015-08-13.log -O /var/www/pgreports/
```

So, is that a bug? Once we have prefix client=%h working good.

Regards.

**Comment by darold** [comment]
Hi Eric,

Please download latest development code, commit 995cdf5 might fix the issue. Let us know.

Regards,

**Comment by e-ruiz** [comment]
Working perfectly!

Thank you Darold, and thank you to make best Postgres log analyzer of this galaxy.

Regards,
=P
