### ISSUE TITLE
Problem to extract files 

### ISSUE THREAD

**Issue by PGDBA2** [dalibo/pgbadger#250]
Hi, 
When I try to extract archive tarball or zip file on Windows (default zip function and 7-zip) or Linux (Ubuntu or SuSE), I always have this kind of message : 

``` 
# tar xzf pgbadger-7.1.tar.gz
gzip: stdin: unexpected end of file
tar: Unexpected EOF in archive
tar: Unexpected EOF in archive
tar: Error is not recoverable: exiting now
``` 
I try previous version until 6.1 and I have the same problem. 

Archives are corrupted ?
```
# md5sum pgbadger-7.1.tar.gz
85fd5fc4643ac6a9c98a463ffaccee08  pgbadger-7.1.tar.gz
```

**Comment by darold** [comment]
Where did you've got this archive release?  
Please download tarball from GitHub, this is the official place for release download now:

    https://github.com/dalibo/pgbadger/releases

Regards,

**Comment by PGDBA2** [comment]
I downloaded it from GitHub, the official page. It's for that reason I sent you th e md5sum.
I still have the problem.
I try also to download the Master but it's the same problem.

**Comment by PGDBA2** [comment]
I gotta feeling the problem it's when I save as Firefox. With Chromium (Ubuntu) and Chrome (Windows), it works.
I will raise the problem to Firefox community.
Thank for your help and for the development.
I'm impatient to test your tool ;)

**Comment by darold** [comment]
Note reproducible.
