### ISSUE TITLE
pgbadger still making third-party HTTP requests.

### ISSUE THREAD

**Issue by fixingshit** [dalibo/pgbadger#251]
https://google-code-prettify.googlecode.com/svn/loader/prettify.css

That URL is loaded other than the big .html blob. This is a serious privacy issue as it will let Google know about every page load of my *internal copy* of pgbadger HTML output. Please, please fix this to be baking in that file instead of remotely requesting it.

**Comment by darold** [comment]
This URL code is part of the prettify.js javascript file, I have no idea about how to remove this call maybe you can help  whatever is your name. It is also possible that this file is not necessary for the flotr2 or bootstrap libraries. Your help is welcome, if you use --extra-files or -X art pgbadger command line it will extract all javascript and CSS file into the output directory. So you will be able to test change in the prettify.js file without having to regenerate a report.

**Comment by darold** [comment]
This is fix with commit 4c5dee2 which replace flotr2 javascript library with jqplot and then the use of code prettify library that was making an access to Google's javascript library.
