### ISSUE TITLE
pgbadger report with different log format

### ISSUE THREAD

**Issue by venkatabn** [dalibo/pgbadger#253]
Hello,

I have a logfile with the format as follows -

2015-09-23 16:20:31 EST[3512]:[-1] db=db01, user=xxx, app=[unknown], client=x.x.x.x LOG: ....

Can i generate a pgbadger report ? If you look above all the lines have [-1] which was due to mistakenly configured log_line_prefix, which has been fixed now, but, i have lots of logfiles with the above format which needs to be analyzed. Please let me know if there is a possibility of generating a pgbadger report. That will be a great help !

Thanks !

**Comment by darold** [comment]
Hi,

You can try the following:

    pgbadger --prefix '%t[%p]:[-1] db=%d, user=%u, app=%a, client=%h '

it should works.

Regards,

**Comment by venkatabn** [comment]
On Fri, Sep 25, 2015 at 6:07 PM, Darold <notifications@github.com> wrote:

> Hi,
>
> You can try the following:
>
> pgbadger --prefix '%t[%p]:[-1] db=%d, user=%u, app=%a, client=%h '
>
> it should works.
>

Thanks, that seems to be working.

Another, question i have is, does pgbadger shows up the avg response time
for the queries taking lesser than 1 second ?

I does generate a graph, but, i would like to know the avg response time of
all the queries including those taking less than a second.

Regards,
Venkata B N

**Comment by darold** [comment]
Hi,

You have the histogram of queries response times in the Top menu. That should be what you are looking for. If you don't have it please upgrade pgBadger, we are currently at version 7.1.

Regards,

**Comment by venkatabn** [comment]
On Thu, Oct 1, 2015 at 5:37 PM, Darold <notifications@github.com> wrote:

> Hi,
>
> You have the histogram of queries response times in the Top menu. That
> should be what you are looking for. If you don't have it please upgrade
> pgBadger, we are currently at version 7.1.
>

Histogram does display the queries response times. What i am looking for is
the response time for queries individually. If the query's response time is
less than a second, it show 0s

I am using pgbadger-7 - not sure if i am using 7.1. Will that make a
difference ?

Thanks,
Venkata B N

**Comment by darold** [comment]
When pgbadger report 0s it should mean 0 millisecond => 0.000 second otherwize it display the millisecond time, for exemple:  4ms. I'm agree that it should be 0ms instead of 0s. Commit 487dbe1 fix that. Thanks

**Comment by venkatabn** [comment]
Thanks for reply.

pgBadger report does display 0s and the corresponding graphs on the right
does show that queries were taking 0.75 ms. I will check the fix. Thanks !
