### ISSUE TITLE
See report for selective timing

### ISSUE THREAD

**Issue by deepakdeore2004** [dalibo/pgbadger#254]
The tool is awesome, I want to request a feature to see the report for selected time. I know we can zoom into graphs. But lets say I want to see full report during selected time then I have to again process the logs by selecting only logs during the time I want.

Would it be easy to add this feature?

**Comment by darold** [comment]
Hi,

Unfortunately not, the report are statics html pages and javascript arrays for charts, but theoretically this might be possible by using json data files. Maybe I can work on this when I'll find enough spare time, but this is a huge work and don't expect to see this feature after a long time.

Regards,

**Comment by deepakdeore2004** [comment]
ok, thanks for the quick reply, will wait for this feature.
