### ISSUE TITLE
dot in dbname and user name

### ISSUE THREAD

**Issue by davidturvey** [dalibo/pgbadger#256]
Hi,

We have some databases and usernames which contain a dot character (eg ```foo.bar``` ). These are not included in the output of pgbadger. 

The issue is similar to #41 where the regex was updated to accept the special character.

I have changed the script on my local machine as follows and it works as expected

```
  '%u' => [('t_dbuser', '([0-9a-zA-Z\_\[\]\-\.]*)')],       # user name
  '%d' => [('t_dbname', '([0-9a-zA-Z\_\[\]\-\.]*)')],     # database name
```

**Comment by darold** [comment]
Hi David,

Thanks, your patch have been applied in commit 149f08e.

Best regards,
