### ISSUE TITLE
canceling statement due to statement timeout

### ISSUE THREAD

**Issue by vd0v1n** [dalibo/pgbadger#257]
Hello.
In section Events are not displayed log entries such as 
2015-11-13 15:47:18.741 EET,"","",,"",,,"",2015-11-13 15:42:50 EET,,,ERROR,,"canceling statement due to statement timeout",,,,,,",,,""
What could be the reason?

**Comment by darold** [comment]
Hello,

This is because cancelled statements have a dedicated report named "Number of cancelled queries". See bottom of "Queries" menu.

Regards,

**Comment by darold** [comment]
After some though I think that when -w or --watch-mode is used, this message must be reported with other errors.  Commit d907aa9 fix that.

**Comment by vd0v1n** [comment]
Thank you!
