### ISSUE TITLE
No SQL traffic with --log-duration command

### ISSUE THREAD

**Issue by vishesh92** [dalibo/pgbadger#259]
I am trying to run pgbadger on my AWS RDS postgresql logs. The graph for `SQL traffic, SELECT traffic, INSERT/UPDATE/DELETE Traffic and Queries duration` is 0 for all the time range.

`pgbadger -I -j 9 --log-duration -p '%t:%r:%u@%d:[%p]:' postgresql.log.2016-01-09-23 -O /output/`

But if I run
`pgbadger -I -j 9  -p '%t:%r:%u@%d:[%p]:' postgresql.log.2016-01-09-23 -O /output/`

The above charts are visible but then there are no `slowest queries` and `Time consuming queries` have zero duration.

Any way to fix this?

**Comment by darold** [comment]
HI,

pgBadger can not do what it is not expected to do. Why did you use a non existing command line option?

     --log_statement=none

and please have a deeper look to the documentation. On usage:
```
        --log-duration         : force pgbadger to associate log entries generated
                                 by both log_duration = on and log_statement = 'all'
```
means that to use this feature you must have log_duration = on and log_statement = 'all' in your configuration file. Note that this is not the right way to obtain the best from pgBadger.

Then take a look at "PostgreSQL configuration" and "log_min_duration_statement, log_duration and log_statement" section in the README file or the man page.

**Comment by darold** [comment]
And if you don't have control on the postgresql.conf configuration file, please post here a part of your log (around 50 lines) to see what can be extracted. If you prefer you can send the log to my private email ( gilles AT darold DOT net )

**Comment by vishesh92** [comment]
I added ` --log_statement=none` by mistake. Have updated the post.
Anyways, I have emailed you the logs.

**Comment by vishesh92** [comment]
And if use `--log-duration`, I do get `slowest queries`.

**Comment by darold** [comment]
There's not duration information in your log and the --log-duration option is only relevant if log_duration = on in your postgresql.conf. For what I see, this is not the case unless you have change the variable later in an other part of the log.

If you can change the postgresql.conf I really recommand you to follow the best practice of pgBadger explained in the documentation. Here the only thing you can have is the reports about number of queries but nothing about their duration, I mean you will just have the "Most frequent queries(N)" report, nothing about slowest and time consuming queries.

**Comment by vishesh92** [comment]
Thanks. Will check if I can the edit postgresql.conf
And I don't think '--log-duration' should effect `SQL Traffic`

**Comment by darold** [comment]
In your context, (from the log I've received), the pgbadger `--log-duration` does not do anything.
