### ISSUE TITLE
"EIQ - QUO character not allowed" issues.

### ISSUE THREAD

**Issue by DBAYoder** [dalibo/pgbadger#261]
I am receiving "EIQ - QUO character not allowed" on several logs each day (hourly logs) on our production server.  The failures are causing queries within the log to not be processed.

Here is an example of one of the logs being parsed in verbose mode:

    DEBUG: Autodetected log format 'csv' from prod-2016-01-19-01.csv
    DEBUG: Output 'html' reports will be written to prod-2016-01-19-01.uconv.html
    DEBUG: Starting to parse log file: prod-2016-01-19-01.csv
    DEBUG: Starting reading file prod-2016-01-19-01.csv...
    FATAL: cannot use CSV on prod-2016-01-19-01.csv, EIQ - QUO character not allowedies: 545965, events: 0
    [==>                      ] Parsed  639306677 bytes of 5418197791 (11.80%), queries: 554346, events: 0
    DEBUG: the log statistics gathering took:129 wallclock secs (128.46 usr +  0.49 sys = 128.95 CPU)
    LOG: Ok, generating html report...
    DEBUG: building reports took:  7 wallclock secs ( 6.34 usr +  0.02 sys =  6.36 CPU)
    DEBUG: the total execution time took: 136 wallclock secs (134.80 usr +  0.51 sys = 135.31 CPU)

Logs are from a PostgreSQL 9.1 server.

Versions used on server:

    perl 5, version 14, subversion 2 (v5.14.2) built for x86_64-linux-thread-multi
    pgBadger version 5.1

Versions used on laptop (moved log to laptop to try on more current version):

    perl 5, version 18, subversion 2 (v5.18.2) built for darwin-thread-multi-2level
    pgBadger version 6.2

Any help is appreciated.

**Comment by darold** [comment]
Hi,

Your versions of pgBadger are old, 5.1 was released on may 2014 and  6.2 on october 2014. Current version is 7.3, please upgrade pgBadger. Let us know if the error is still present after the upgrade.

Best regards.

**Comment by DBAYoder** [comment]
Sorry, I did not realize I had not retrieved the latest version when I did a brew install pgdbadger on my Mac (Even after doing a brew update/brew upgrade pgdbager, the version installed was only 7.1).  On 7.1 it also gave the same error when parsing the log.  The logs are quite long (>6 million lines), but I did manage to isolate the line that was causing the failure.  It appears that the log file is getting the start of a new log entry in the middle of a query being written out to the log.  Specifically, an insert statement is being run and in the middle of a text value being printed to the log (i.e. after the initial single quote ('), but before the final one) another entry starts without an intervening new line.  

So, my question has been altered.  My first priority would be to discover the cause of the bad line in the log and prevent that from happening, but barring being able to accomplish that, is there a way for me to specify to pgbadger to ignore any lines that are incomplete or malformed?

Thank you.

**Comment by darold** [comment]
Hi,

pgBadger stop to parse the log because it is not more a valid CSV file, I don't know the reason but it stop because Text::CSV Perl module fail to return a valid content. You have to fix the csv log file. If you don't use the CSV format with any other application, it is better to use stderr log_destination.

Best regards,

**Comment by DBAYoder** [comment]
ok, thanks so much for your responses (and PGBadger!)

**Comment by blunney1** [comment]
I had a similar issue with RDS logs, where the log line contained "[Your log message was truncated]".  (pgBadger 9.1)
