### ISSUE TITLE
Chart rendering in OSX

### ISSUE THREAD

**Issue by eMerzh** [dalibo/pgbadger#263]
hi, 
i'm a big fan of the tool, but i was trying to make a demo using firefox osx and i got real issues with firefox... same issue using chrome (latest versions)
not sure you guys can do smth about it, but i wanted to report it ...

you can see the following gif
![charts on mouse over](https://cloud.githubusercontent.com/assets/177003/12660745/a32a4c6e-c615-11e5-8d29-aaa1738df658.gif)

(also note that the chart itself is not at the optimal resolution compared to the fonts ... on a retina screen)

**Comment by darold** [comment]
Hi,

Please upgrade to latest 7.3 release, this have been solved by changing the javascript library. This was an issue common to all browsers and the flotr2 library.

Best regards,

**Comment by eMerzh** [comment]
ok cool, can close then...
i was using the sample reports from the website .....
