### ISSUE TITLE
gzipped log file no more recognized after upgrade to 8.0

### ISSUE THREAD

**Issue by birkosan** [dalibo/pgbadger#266]
I use pgbadger with gzipped logfiles and now, after upgrade, I get the error:
DEBUG: Unknown pgbouncer line format:

**Comment by darold** [comment]
Thanks for the report. Last commit  06c405f might fix this issue. Please use latest development code and let me know.

Best regards,

**Comment by birkosan** [comment]
It's working.
Thank you!
