### ISSUE TITLE
Parsing problem after upgrade from 7.0 to 8.0

### ISSUE THREAD

**Issue by pyvitre** [dalibo/pgbadger#268]
Hi,

We upgrade PGBadger from 7.0 to 8.0.
We have some issues with the number of queries compute by pgbadger. 
With the same log file, we can see more than 50 % difference.

So we test each version between 7.0 and 8.0, you can see the result below :
 
```
/tmp/pgbadger_test/pgbadger-7.0/pgbadger -f syslog -o /tmp/index1.html /tmp/postgresql-2016-03-15.log
[========================>] Parsed 58051477 bytes of 58051477 (100.00%), queries: 71044, events: 21

/tmp/pgbadger_test/pgbadger-7.1/pgbadger -f syslog -o /tmp/index1.html /tmp/postgresql-2016-03-15.log
[========================>] Parsed 58051477 bytes of 58051477 (100.00%), queries: 71044, events: 21

/tmp/pgbadger_test/pgbadger-7.2/pgbadger -f syslog -o /tmp/index1.html /tmp/postgresql-2016-03-15.log
[========================>] Parsed 58051477 bytes of 58051477 (100.00%), queries: 31783, events: 21

/tmp/pgbadger_test/pgbadger-7.3/pgbadger -f syslog -o /tmp/index1.html /tmp/postgresql-2016-03-15.log
[========================>] Parsed 58051477 bytes of 58051477 (100.00%), queries: 31783, events: 21

/tmp/pgbadger_test/pgbadger-8.0/pgbadger -f syslog -o /tmp/index1.html /tmp/postgresql-2016-03-15.log
[========================>] Parsed 58051477 bytes of 58051477 (100.00%), queries: 31783, events: 21

```
We don't notice evolution in the changelog between 7.1 and 7.2 that could explain this changment.

We think about line log format so we try a small log file with representative lines : 

```
Version 7.0 : 
Query peak : 30 queries/s at 2016-03-15 02:04:54

Version 8.0 : 
Query peak : 18 queries/s at 2016-03-15 02:04:54
```

We extract only logs at 02:04:54 ( grep  "Mar 15 02:04:54" postgresql-2016-03-15.log > postgresql-2016-03-15_020454.log )

And try to analyse this file ...

```
/tmp/pgbadger_test/pgbadger-7.0/pgbadger -f syslog -o /tmp/index1.html /tmp/postgresql-2016-03-15_020454.log
[========================>] Parsed 27100 bytes of 27100 (100.00%), queries: 30, events: 0
Query peak : 30 queries/s at 2016-03-15 02:04:54

/tmp/pgbadger_test/pgbadger-8.0/pgbadger -f syslog -o /tmp/index1.html /tmp/postgresql-2016-03-15_020454.log
[========================>] Parsed 27100 bytes of 27100 (100.00%), queries: 30, events: 0
Query peak : 30 queries/s at 2016-03-15 02:04:54
```

... And there is no problem, but if we try 1 minute ( grep  "Mar 15 02:04:" postgresql-2016-03-15.log > postgresql-2016-03-15_0204.log )

```
/tmp/pgbadger_test/pgbadger-7.0/pgbadger -f syslog -o /tmp/index1.html /tmp/postgresql-2016-03-15_0204.log
[========================>] Parsed 59001 bytes of 59001 (100.00%), queries: 52, events: 0
Query peak : 30 queries/s at 2016-03-15 02:04:54

/tmp/pgbadger_test/pgbadger-8.0/pgbadger -f syslog -o /tmp/index1.html /tmp/postgresql-2016-03-15_0204.log
[========================>] Parsed 59001 bytes of 59001 (100.00%), queries: 48, events: 0
Query peak : 30 queries/s at 2016-03-15 02:04:54
```

... The peak is good, but not the number of query
And with 10 minutes ( grep  "Mar 15 02:0" postgresql-2016-03-15.log > postgresql-2016-03-15_020.log )

```
/tmp/pgbadger_test/pgbadger-7.0/pgbadger -f syslog -o /tmp/index1.html /tmp/postgresql-2016-03-15_020.log
[========================>] Parsed 272423 bytes of 272423 (100.00%), queries: 293, events: 0

/tmp/pgbadger_test/pgbadger-8.0/pgbadger -f syslog -o /tmp/index1.html /tmp/postgresql-2016-03-15_020.log
[========================>] Parsed 272423 bytes of 272423 (100.00%), queries: 184, events: 0
Query peak : 20 queries/s at 2016-03-15 02:04:54
```

So ... 
It didn't seem to be a log format problem because the query peak and the query number are good for small log.

Did we miss some change in the config ?

Thank you

Pierre-Yves

PS : 
Pg 9.2.13-1.pgdg80
log_line_prefix = ' user=%u,db=%d '
log_destination = 'syslog'
lc_messages = 'en_US.UTF-8'

**Comment by darold** [comment]
Hi Pierre-Yves,

Please send the postgresql-2016-03-15_020.log resulting log file to my private email gilles@darold.net, I can not answer surely without looking at the log to find the commit or unresolved bug responsible of this behavior.

Best regards,

**Comment by pyvitre** [comment]
Hi,

I try to anonymise my log and I send it to you.

Py

**Comment by darold** [comment]
I was able to reproduce your issue with log file from issue #270 , version prior 7.2 was missing some queries, this the reason why you have this query count difference.

**Comment by pyvitre** [comment]
Seems to be good with the last commit.
I will generate all my report tomorrow with the new version before closing this issue.

Best regards,
