### ISSUE TITLE
 I have a problem with temporary files report

### ISSUE THREAD

**Issue by luannicolini** [dalibo/pgbadger#270]
First I would like to know if I can here report a problem because I'm  new here.
When upgrading from 7.1 to 8.0 pgbadger the report of temporary file does not show-statement that generated, but shows "SET TO LOCAL statement_timeout To ' ';"
I know there were some updates in temporary files on 7.2 pgbadger and I'm  error occurs from version 7.2 forward. In the log of the postgresql-statement that creates the temporary file is different from that shown in pgbager.
Thank you and forgive me if I'm wrong, you may need a log file to test, I'm waiting for new instructions.

**Comment by darold** [comment]
Yes this is the right place to post issues. Can you post here the relevant part of your log to reproduce the issue? If you need privacy on your log, you can sent it to my private email gilles@darold.net.

Regards,

**Comment by luannicolini** [comment]
Hello,
I sent the instructions to your email.
Thank you.

**Comment by darold** [comment]
Last commit 03fb0b9 might fix this issue.

Thanks

**Comment by luannicolini** [comment]
Thank you. It worked perfect now.
