### ISSUE TITLE
How do you install without root permissions?

### ISSUE THREAD

**Issue by cameronrulten** [dalibo/pgbadger#271]
How can one install into a custom directory i.e. not the system /usr/ directory or subdirectories like /usr/local

**Comment by cameronrulten** [comment]
I solved this after finding the DESTDIR command line variable.
To install into a local directory called build, I simply ran:
perl Makefile.PL DESTDIR='build/'
It would be good to include instructions for building into a non-standard directory in your README as sometimes people don't have root permissions.

**Comment by darold** [comment]
An other possibility is to just copy the pgbadger file in any place you want, for exemple ~/bin/ . pgBadger comes as a single Perl script, other files from the source tree are not mandatory.

Best regards
