### ISSUE TITLE
%q in log_line_prefix not handled correctly

### ISSUE THREAD

**Issue by mclei** [dalibo/pgbadger#272]
Default PostgreSQL log_line_prefix on Debian is: '%t [%p-%l] %q%u@%d '.
%q means "stop here in non-session processes".

It means that for example auto vacuums or analyze are logged without user@database:
```
2016-04-12 06:23:29 CEST [29441-2] LOG:  automatic vacuum of table "test.pg_catalog.pg_class": index scans: 1
2016-04-12 06:24:37 CEST [29443-2] LOG:  automatic analyze of table "test.pg_catalog.pg_attribute" system usage: CPU 0.03s/0.19u sec elapsed 9.95 sec
```

And pgbadger ignores these lines as %q is simply removed from line parsing regexp list and there is no user@database in the log line.

**Comment by darold** [comment]
The stop here placeholder is only supported with default pgBader prefix: `'%t [%p]: [%l-1] '`, I mean when there is no `--prefix` parameter and that your log respect this default prefix.

**Comment by mclei** [comment]
I do not understand your answer. Yes I know that if I change log_line_prefix to recommended it will work. But I have several servers with default configuration and months of logs in default format and want to analyze them. So I was looking for solution without changing default prefix.

If it is not possible to solve it, just close this issue. I have created it, because it is not answered anywhere. Your answer could be also answer.

**Comment by darold** [comment]
This is not possible, you have to respect the prefix requirement. To be able to parse your old logs you can execute the following command, it might reformat your log files as expected by pgBadger:

    perl -p -i -e 's/\] LOG:/\] \@ LOG:/'  /var/log/postgresql/postgresql-*.log

Please test the command on a sample log before.

Best regards,
