### ISSUE TITLE
Windows carriage return not handled

### ISSUE THREAD

**Issue by keithf4** [dalibo/pgbadger#273]
Was seeing some long running queries just showing up as
```
SELECT;
```
in the long running query section. Went back in the original logs and found they had the return carriage character showing up in them
```
2016-04-13 14:10:16.213 GMTLOG:  duration: 4461678.087 ms  execute <unnamed>: select^M
                        ob.identifier as "identifier",^M
                        i.code as "code",^M
                        CASE^M
[...]
```
Checking to see if that can be fixed in the app code, but wondered if that may be able to be handled in pgbadger as well.

**Comment by darold** [comment]
This is not a carriage return issue, they are all remove by pgbadger. The problem here comes from your log format. Your log_line_prefix is a single %t which is not enough.

Best regards,

**Comment by keithf4** [comment]
Hmm... It was able to parse all other queries without the ^M character just fine.

I did actually change the log_line_prefix to something more useful today. Will see how the reports look tomorrow.
