### ISSUE TITLE
Allow simultaneous pgbadger instances

### ISSUE THREAD

**Issue by qdw** [dalibo/pgbadger#279]
Thanks for this awesome tool!

From my reading of code (and also from experience!) I take it you can't run more than one simultaneous instance of pgbadger per machine. Why is this? I often want to take two or more sets of logs from different machines, then process them in parallel.

**Comment by darold** [comment]
Hi,

You can run multiple instance of pgbadger on a single machine, this is not a problem. The only thing you have to take care is to provide a dedicated directory for the pid lock file. Use option: --pid-dir to write the pgbadger.pid file in different locations.

Best regards

**Comment by qdw** [comment]
Oh, excellent! Thanks so much!

> On May 27, 2016, at 1:54 PM, Darold <notifications@github.com> wrote:
> 
> Hi,
> 
> You can run multiple instance of pgbadger on a single machine, this is not a problem. The only thing you have to take care is to provide a dedicated directory for the pid lock file. Use option: --pid-dir to write the pgbadger.pid file in different locations.
> 
> Best regards
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub <https://github.com/dalibo/pgbadger/issues/279#issuecomment-222250915>, or mute the thread <https://github.com/notifications/unsubscribe/AAET1Hx4C_6S0FlN7C9ZTcZbwjA1b64qks5qF1oKgaJpZM4Ioucw>.
> 


--
Quinn Weaver
PostgreSQL Experts, Inc.
http://pgexperts.com/ <http://pgexperts.com/>
