### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Nikhil14** [dalibo/pgbadger#283]
C:\Users\nmurarka\Desktop\pgbadger-8.0>pgbadger
FATAL: an other process is already started or remove the file, see C:\Users\nmurarka\AppData\Local\Temp/pgbadger.pid

**Comment by darold** [comment]
Hi,

You need to remove this file manually, this is to prevent simultaneous run of pgbadger. Usually pgbadger remove this file when it terminates normally. After a crash or a kill the file may remain .

**Comment by Nikhil14** [comment]
Okay thanks it works after removing this file
