### ISSUE TITLE
PgBadger - Latency Percentile meaning

### ISSUE THREAD

**Issue by HCOUROUSSE** [dalibo/pgbadger#284]
Hi, could-you please explain what is the meaning of Latency Percentile(90), Latency Percentile(95), Latency Percentile(99) values. I can't find precision about them in the documentation. 

For exemple :
I saw than between 16h and 17h there are 4 269 select queries with 6s2ms average and 15m46s max duration. But i don't understand Latency Percentile values. 
My PostgresQL server have 24 cpu..
Thank you. Henri

Hour 	Count 	Min duration 	Max duration 	Avg duration 	Latency Percentile(90) 	Latency Percentile(95) 	Latency Percentile(99)
16 	4,269 	6s2ms 	15m46s 	27s499ms 	1h40m59s 	1h51m31s 	2h12m33s

And the Slowest individual query is
Rank 	Duration 	Query
1 	15m46s 	
SELECT rpct_id FROM t_res_prod_controlables WHERE ...;

**Comment by darold** [comment]
Hi,

This is the sum of queries duration per minute at 90/95/99 percent of all queries in an hour. 

Regards

**Comment by HCOUROUSSE** [comment]
Thank you Gilles
