### ISSUE TITLE
corrupted LAST_PARSED?

### ISSUE THREAD

**Issue by brafaeloliveira** [dalibo/pgbadger#285]
Hi! I've tried this several times, and after some correct increments, somehow LAST_PARSED file loses the first 3 characters and messes up everything... 

pgbadger -I /pg_log/postgresql*.log -O /reports/
[========================>] Parsed 2060816 bytes of 2060816 (100.00%), queries: 142, events: 0
LOG: Ok, generating HTML daily report into /reports//2016/06/23/...
LOG: Ok, generating HTML weekly report into /reports//2016/week-26/...
LOG: Ok, generating global index to access incremental reports...

pgbadger -I /pg_log/postgresql*.log -O /reports/
[========================>] Parsed 9205803 bytes of 9205803 (100.00%), queries: 0, events: 0
[========================>] Parsed 2600941 bytes of 2600941 (100.00%), queries: 193, events: 0
[========================>] Parsed 2296711 bytes of 2296711 (100.00%), queries: 750, events: 6
[========================>] Parsed 1509476 bytes of 1509476 (100.00%), queries: 609, events: 0
[========================>] Parsed 1416631 bytes of 1416631 (100.00%), queries: 641, events: 0
[========================>] Parsed 3333476 bytes of 3333476 (100.00%), queries: 878, events: 11
[========================>] Parsed 1255288 bytes of 1255288 (100.00%), queries: 335, events: 4
LOG: Ok, generating HTML daily report into /reports//2016/06/23/...
LOG: Ok, generating HTML daily report into /reports//2016/06/24/...
LOG: Ok, generating HTML daily report into /reports//2016/06/25/...
LOG: Ok, generating HTML daily report into /reports//2016/06/26/...
LOG: Ok, generating HTML daily report into /reports//2016/06/27/...
LOG: Ok, generating HTML daily report into /reports//2016/06/28/...
LOG: Ok, generating HTML daily report into /reports//6/01/10/...
LOG: Ok, generating HTML weekly report into /reports///...
LOG: Ok, generating HTML weekly report into /reports//2016/week-26/...
LOG: Ok, generating HTML weekly report into /reports//2016/week-27/...
LOG: Ok, generating global index to access incremental reports...

pgbadger -I /pg_log/postgresql*.log -O /reports/
WARNING: can't read file /reports//LAST_PARSED.tmp, No such file or directory
HINT: maybe there's no new entries in your log since last run.
LOG: Ok, generating global index to access incremental reports...

ls -al /reports/
total 712
drwxrwxrwx  4 owner    owner  12288 Jun 28 13:01 .
drwxrwxrwx  5 owner    owner   4096 Jun 22 15:01 ..
drwxr-xr-x 21 owner    owner    4096 Jun 28 12:59 2016
drwxr-xr-x  3 owner    owner    4096 Jun 28 12:57 6
-rw-r--r--  1 owner    owner  694655 Jun 28 13:01 index.html
-rw-r--r--  1 owner    owner     181 Jun 28 12:57 LAST_PARSED

more /reports/LAST_PARSED
6-01-10 05:20:07        9205803 6-01-10 05:20:07 WET [29651]: [3-1] db=template1,user=postgres LOG:  disconnection: session time: 0:00:00.006 user=postgres database=template1 host=[local]

**Comment by darold** [comment]
Hi,

What is the version reported by: pgbadger -V

**Comment by brafaeloliveira** [comment]
Hi. Thank you for the reply.

I installed it last week:

sudo nano /etc/apt/sources.list.d/pgdg.list
     (paste deb http://apt.postgresql.org/pub/repos/apt/ precise-pgdg main)
sudo apt-get install wget ca-certificates
wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
sudo apt-get update
sudo apt-get install pgbadger
pgbadger -V 

pgBadger version 8.1


cat /etc/*release

DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=12.04
DISTRIB_CODENAME=precise
DISTRIB_DESCRIPTION="Ubuntu 12.04.5 LTS"
NAME="Ubuntu"
VERSION="12.04.5 LTS, Precise Pangolin"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu precise (12.04.5 LTS)"
VERSION_ID="12.04"

uname -a

Linux ###### 3.2.0-101-generic #141-Ubuntu SMP Thu Mar 10 21:43:24 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

**Comment by darold** [comment]
Please fix manually the year part of the date in the LAST_PARSED file.

**Comment by darold** [comment]
Last commit c7e21f4 might remove and other possible case of truncated date in LAST_PARSED file. Let us know if the issue appears again after pgbadger upgrade. To fix manually the LAST parsed file, replace the two occurrences of  6-01-10 by 2016-01-10 in the file.

**Comment by brafaeloliveira** [comment]
Ok, i ran it with commit c7e21f4 several times in different server and it's ok, now!
Thank you very much. :)
