### ISSUE TITLE
Multiline queries are not parsed

### ISSUE THREAD

**Issue by dpiscitelli** [dalibo/pgbadger#287]
Hi,

I have this type of queries in postresql.log
2016-06-30 14:09:27 CEST alfresco@10.21.92.76(51166) (dbalfresco) [0] LOG:  duration: 0.388 ms  bind S_26: select
                    node.id             as id,
                    node.version        as version,
                    store.id            as store_id,
                    store.protocol      as protocol,
                    store.identifier    as identifier,
                    node.uuid           as uuid,
                    node.type_qname_id  as type_qname_id,
                    node.locale_id      as locale_id,
                    node.acl_id         as acl_id,
                    txn.id              as txn_id,
                    txn.change_txn_id   as txn_change_id,
                    node.audit_creator  as audit_creator,
                    node.audit_created  as audit_created,
                    node.audit_modifier as audit_modifier,
                    node.audit_modified as audit_modified,
                    node.audit_accessed  as audit_accessed

                from
                    alf_node node
                    join alf_store store on (store.id = node.store_id)
                    join alf_transaction txn on (txn.id = node.transaction_id)
                where
                    node.id = $1
2016-06-30 14:09:28 CEST alfresco@10.21.92.76(51148) (dbalfresco) [0] LOG:  duration: 0.369 ms  bind <unnamed>: select
                    node.id                    as node_id,
                    node.version               as node_version,
                    aspects.qname_id           as qname_id

                from
                    alf_node node
                    join alf_node_aspects aspects on (aspects.node_id = node.id)
                 WHERE  aspects.node_id in
                        (
                            $1
                        ,
                            $2
                        ,
                            $3
                        ,
                            $4
                        ,
                            $5
                        ,
                            $6
                        ,
                            $7
                        ,
                            $8
                        ,
                            $9
                        )
2016-06-30 14:09:28 CEST alfresco@10.21.92.76(51148) (dbalfresco) [0] DETAIL:  parameters: $1 = '3228711', $2 = '3231864', $3 = '3232356', $4 = '3270934', $5 = '3867615', $6 = '4575220', $7 = '4575340', $8 = '4614072', $9 = '4650115'

They are not parsed by pgbadger... bug or I miss something ??

Thanks for yout help

**Comment by darold** [comment]
What pgbadger command are you using?

**Comment by dpiscitelli** [comment]
Thx for your reply

My Conf
Postgresql 9.3, pgbadger 8.1

log_destination = 'stderr'   
log_line_prefix = '%t %u@%r (%d) [%x] '
log_checkpoints = on
log_connections = on
log_disconnections = on
log_min_duration_statement = 1000       # -1 is disabled, 0 logs all statements
log_lock_waits = on
log_temp_files = 0


My command line
perl pgbadger --prefix '%t %u@%r (%d) [%x] ' /errorbdd/postgres/pg_alfresco/postgresql-test.log

David

**Comment by darold** [comment]
One of the mandatory field is %p (pid), without this field pgBadger is not able to parse your file. You can replace the %x by %p in your log line prefix unless you are using the transaction id for an other tool.

**Comment by dpiscitelli** [comment]
It works much better ! Thx

Last, what i the best way to have support on pgbadger ?

**Comment by darold** [comment]
Support on pgbadger is available on the pgbadger mailing list pgbadger@googlegroups.com for free. If you need professional support you can contact my company Dalibo.com or any other postgresql company available on the following page:  https://www.postgresql.org/support/professional_support/

Best regards,
