### ISSUE TITLE
pgbadger -I mode cannot work

### ISSUE THREAD

**Issue by ghotiv** [dalibo/pgbadger#288]
pgbadger -V
pgBadger version 8.1
the command 
/usr/local/bin/pgbadger  -I -q /var/log/postgresql/* -O /var/www/html/pgbadger_log/

[========================>] Parsed 9892765 bytes of 9892765 (100.00%), queries: 0, events: 0
WARNING: can't read file /var/www/html/pgbadger_log//LAST_PARSED.tmp, No such file or directory
HINT: maybe there's no new entries in your log since last run.
LOG: Ok, generating global index to access incremental reports...

file in /var/www/html/pgbadger_log
2016  index.html  LAST_PARSED

look the LAST_PARSED 
/var/www/html/pgbadger_log/LAST_PARSED 
2016-07-14 22:25:57     3529170 2016-07-14 22:25:57 CST [2812]: [28365-1] user=o**,db=w**,app=[unknown],client=10.** LOG:  duration: 302.531 ms  statement: SELECT "hgs_buyer_info".id FROM "hgs_buyer_info" WHERE (("hgs_buyer_info"."user_eshop_prime_key" = '***')  AND  ("hgs_buyer_info"."shop_type" = 't***')) ORDER BY "hgs_buyer_info"."latest_order_time" DESC

but the time now is 2016-07-15,  
/var/www/html/pgbadger_log/2016/07# ls
14

there is no data 07-15 report

**Comment by darold** [comment]
Hi,

This is a warning only, it means that pgbadger can not find any new entry to parse in your log file. What is the result of the command: `ls -la /var/log/postgresql/*`

Regards,

**Comment by ghotiv** [comment]
tks to response to me

root@iZ23qvkl7kqZ:~# ls -la /var/log/postgresql/*
-rw-r----- 1 postgres adm 4087226904 Jul 15 15:37 /var/log/postgresql/postgresql-9.1-main.log
-rw-r----- 1 postgres adm    9892765 Jul 10 06:25 /var/log/postgresql/postgresql-9.1-main.log.1
-rw-r----- 1 postgres adm    2264509 Jul  3 06:25 /var/log/postgresql/postgresql-9.1-main.log.2.gz
-rw-r----- 1 postgres adm     292550 Jun 27 06:25 /var/log/postgresql/postgresql-9.1-main.log.3.gz
-rw-r----- 1 postgres adm     160438 Jun 19 06:25 /var/log/postgresql/postgresql-9.1-main.log.4.gz

root@iZ23qvkl7kqZ:~# /usr/local/bin/pgbadger -I /var/log/postgresql/* -O /var/www/html/pgbadger_log/
[=>                       ] Parsed  815383 bytes of 9892765 (8.24%), queries: 0,[===>                     ] Parsed 1541776 bytes of 9892765 (15.58%), queries: 0[=================>       ] Parsed 7339729 bytes of 9892765 (74.19%), queries: 0[===================>     ] Parsed 8079443 bytes of 9892765 (81.67%), queries: 0[=====================>   ] Parsed 8820075 bytes of 9892765 (89.16%), queries: 0[=======================> ] Parsed 9688007 bytes of 9892765 (97.93%), queries: 0[========================>] Parsed 9892765 bytes of 9892765 (100.00%), queries: 0, events: 0
[=================>       ] Parsed 7090335 bytes of 9786746 (72.45%), queries: 0[===================>     ] Parsed 7801366 bytes of 9786746 (79.71%), queries: 0[=====================>   ] Parsed 8605985 bytes of 9786746 (87.94%), queries: 0[=======================> ] Parsed 9473991 bytes of 9786746 (96.80%), queries: 0[========================>] Parsed 9786746 bytes of 9786746 (100.00%), queries: 0, events: 0
[=>                       ] Parsed  441679 bytes of 6816101 (6.48%), queries: 0,[====>                    ] Parsed 1172467 bytes of 6816101 (17.20%), queries: 0[======>                  ] Parsed 1865257 bytes of 6816101 (27.37%), queries: 0[=========>               ] Parsed 2602564 bytes of 6816101 (38.18%), queries: 0[===========>             ] Parsed 3407534 bytes of 6816101 (49.99%), queries: 0[==============>          ] Parsed 4177974 bytes of 6816101 (61.30%), queries: 0[=================>       ] Parsed 4965208 bytes of 6816101 (72.85%), queries: 0[===================>     ] Parsed 5667469 bytes of 6816101 (83.15%), queries: 0[======================>  ] Parsed 6420351 bytes of 6816101 (94.19%), queries: 0[========================>] Parsed 6816101 bytes of 6816101 (100.00%), queries: 0, events: 0
[==>                      ] Parsed  399876 bytes of 3529170 (11.33%), queries: 0[========>                ] Parsed 1233040 bytes of 3529170 (34.94%), queries: 0[=============>           ] Parsed 2025306 bytes of 3529170 (57.39%), queries: 0[==================>      ] Parsed 2743049 bytes of 3529170 (77.73%), queries: 0[=======================> ] Parsed 3475037 bytes of 3529170 (98.47%), queries: 0[========================>] Parsed 3529170 bytes of 3529170 (100.00%), queries: 0, events: 0
WARNING: can't read file /var/www/html/pgbadger_log//LAST_PARSED.tmp, No such file or directory
HINT: maybe there's no new entries in your log since last run.
LOG: Ok, generating global index to access incremental reports...

run the command again but html cannot updte，
about 2016-07-15 10:5  i have delete all  pgbadger_log，and run the command，generate it

now at  about 2016-07-15 15:40  run the command with -I mode
it is still 
2016-07-15 10:52:19 Last query

**Comment by darold** [comment]
Oh, ok, you are not using any prefix in pgbadger command line but you do not use the default one . Looking at your last parsed line you need to redefine it. What is the values of the log_destination and log_line_prefix configuration directive in postgresql.conf?

**Comment by ghotiv** [comment]
#log_destination = 'stderr'
log_line_prefix = '%t [%p]: [%l-1] user=%u,db=%d,app=%a,client=%h '

**Comment by darold** [comment]
Strange, please post a log entry.

**Comment by ghotiv** [comment]
2016-07-15 16:26:32 CST [15294]: [21780-1] user=odoo,db=w****,app=[unknown],client=10.162.38.** LOG:  duration: 0.461 ms  statement: SELECT MAX(CASE WHEN perm_write THEN 1 ELSE 0 END)   FROM ir_model_access a   JOIN ir_model m ON (m.id = a.model_id)   JOIN res_groups_users_rel gu ON (gu.gid = a.group_id)  WHERE m.model = 'res.users'    AND gu.uid = 29    AND a.active IS True

**Comment by ghotiv** [comment]
the LAST_PARSED now
2016-07-15 10:52:19     3529170 2016-07-15 10:52:19 CST [11285]: [31229-1] user=odoo,db=wms20160109,app=[unknown],client=10.162.38.47 LOG:  duration: 0.019 ms  statement: COMMIT

**Comment by darold** [comment]
Ok, my bad, I've misinterpreted the last parsed line. What is the output of the following command?

`/usr/local/bin/pgbadger -v -I /var/log/postgresql/postgresql-9.1-main.log -O /var/www/html/pgbadger_log/`

**Comment by ghotiv** [comment]
root@iZ23qvkl7kqZ:/var/www/html/pgbadger_log# /usr/local/bin/pgbadger -v -I /var/log/postgresql/postgresql-9.1-main.log -O /var/www/html/pgbadger_log/
DEBUG: Autodetected log format 'stderr' from /var/log/postgresql/postgresql-9.1-main.log
DEBUG: Output 'html' reports will be written to out.html
DEBUG: this file has already been parsed: /var/log/postgresql/postgresql-9.1-main.log, timestamp 2016-07-14 18:13:36 read at offset 3529170 is lower than saved timestamp: 2016-07-15 10:52:19
DEBUG: the log statistics gathering took: 0 wallclock secs ( 0.04 usr +  0.00 sys =  0.04 CPU)
WARNING: can't read file /var/www/html/pgbadger_log//LAST_PARSED.tmp, No such file or directory
HINT: maybe there's no new entries in your log since last run.
LOG: Ok, generating global index to access incremental reports...
DEBUG: building reports took:  0 wallclock secs ( 0.01 usr +  0.00 sys =  0.01 CPU)
DEBUG: the total execution time took:  0 wallclock secs ( 0.05 usr +  0.00 sys =  0.05 CPU)

**Comment by darold** [comment]
There is an unconsistency between the timestamp found at the start offset and the timestamp in the last parse file.

Please update pgbadger with latest development code from github and as a workaround to be able to parse again this log proceed as follow.

Edit the postgresql-9.1-main.log and go to the start offset (3529170), you must see a log entry starting with `2016-07-14 18:13:36` and not `2016-07-15 10:52:19` as expected by pgbadger. To go at this offset just enter `:goto 3529170` into vi editor.

If the last information reported by pgbadger is really at 2016-07-15 10:52:19, you need to find this line in the log file and replace the offset in the LAST_PARSED file with the right offset found in your log at this position. To get the offset of the current position in the log file file, alway in vi, type: `g and ctrl+g` the last field reported by vi will give you the position.

If the pgbadger's report really ends at 2016-07-14 18:13:36 you have to replace the timestamp (first field) and the log line in the LAST_PARSED file. The offset remain the same.

**Comment by ghotiv** [comment]
i install the code from git at date 07-14

**Comment by ghotiv** [comment]
goto 3529170
        d3.layout.histogram=function(){var frequency=true,valuer=Number,ranger=d3_layout_histogramRange,binner=d3_layout_histogramBinSturges;function histogram(

**Comment by darold** [comment]
Sorry, maybe I was not clear enough, I mean goto offset 3529170 of your log file /var/log/postgresql/postgresql-9.1-main.log

**Comment by ghotiv** [comment]
![2016-07-15 18 23 42](https://cloud.githubusercontent.com/assets/7190138/16871406/523ae588-4ab9-11e6-96d5-5cbf6e1d3804.png)

**Comment by ghotiv** [comment]
![2016-07-15 18 36 01](https://cloud.githubusercontent.com/assets/7190138/16871699/0706ebf0-4abb-11e6-967b-a42a70980d80.png)

**Comment by darold** [comment]
Perhaps a more simpler manner to correct this issue is to remove the /var/www/html/pgbadger_log/LAST_PARSED file and run pgbadger as follow:
```
/usr/local/bin/pgbadger -v -b '2016-07-15 10:52:20' -I /var/log/postgresql/postgresql-9.1-main.log -O /var/www/html/pgbadger_log/
```

this will force pgbadger to read the entire file but skip all entries before 2016-07-15 10:52:20

**Comment by ghotiv** [comment]
tks，it works now
DEBUG: the log statistics gathering took:620 wallclock secs (611.91 usr +  3.85 sys = 615.76 CPU)
LOG: Ok, generating HTML daily report into /var/www/html/pgbadger_log//2016/07/15/...
LOG: Ok, generating HTML weekly report into /var/www/html/pgbadger_log//2016/week-29/...
LOG: Ok, generating global index to access incremental reports...
DEBUG: building reports took: 38 wallclock secs (37.84 usr +  0.34 sys = 38.18 CPU)
DEBUG: the total execution time took: 658 wallclock secs (649.75 usr +  4.19 sys = 653.94 CPU)

but i must alter the time everyday, then run the command?

**Comment by darold** [comment]
No, now you can proceed as before (without the -b option) this was just to unlock the situation.

**Comment by ghotiv** [comment]
tks a lot, it works now

**Comment by ghotiv** [comment]
I try it again, it seems like that
first,delete LAST_PARSED,then run
`/usr/local/bin/pgbadger -v -b '2016-07-15 18:29:25' -I /var/log/postgresql/postgresql-9.1-main.log -O /var/www/html/pgbadger_log/`
works,

then run 
`/usr/local/bin/pgbadger -I -q /var/log/postgresql/postgresql-9.1-main.log -O /var/www/html/pgbadger_log/`
works 

but when i parse   /var/log/postgresql/*
`/usr/local/bin/pgbadger -I -q /var/log/postgresql/* -O /var/www/html/pgbadger_log/`
works again

then i parse   /var/log/postgresql/*  once again
`/usr/local/bin/pgbadger -I -q /var/log/postgresql/* -O /var/www/html/pgbadger_log/`
it does not work

**Comment by darold** [comment]
Please replace -q with -v and past here the output.

**Comment by darold** [comment]
Hi,

I have fully rewritten the last file parsed detection mechanism, please download latest development code from github and let me know if your issue is solved.

Also not that if you are running pgbadger each days it is better to remove old PostgreSQL log files from the command like as follow:

    /usr/local/bin/pgbadger -I -q -O /var/www/html/pgbadger_log/  `find /var/log/postgresql/ -name 'postgresql-9.1-main.log*' -mtime -1`

**Comment by ghotiv** [comment]
dear,darold
tks a lot,this tool realy helps us much
our host will change,I will try this again and tell you the result
