### ISSUE TITLE
bad html report

### ISSUE THREAD

**Issue by fdbxa** [dalibo/pgbadger#290]
Hello.

Bad html report in page "Most frequent queries (N)"
![547](https://cloud.githubusercontent.com/assets/20556697/16985122/2c975970-4e87-11e6-86cb-4dfd0c4cb750.JPG)

**Comment by darold** [comment]
There is sometime some queries that get out of the screen because there is a long non breakable string (aka no space character). I can not do anything for that without breaking the exact query, but maybe there is a solution to not break the displayed list when there is a breaking example.

**Comment by fdbxa** [comment]
Full query:
http://pastebin.com/KQdgK2d3
If I double click in this icon
![547](https://cloud.githubusercontent.com/assets/20556697/17014313/a82383ca-4f2c-11e6-9325-452c1ea4bdcd.JPG)
html report is normalized
![789456](https://cloud.githubusercontent.com/assets/20556697/17014503/8f67d95c-4f2d-11e6-9f3b-2dedb8b61b23.JPG)
Maybe html code help debug this problem:
http://pastebin.com/bLVBKeyn

**Comment by darold** [comment]
I don't think that the problem comes from the normalized query, formatted or not, but rather on the hidden examples of the query.

**Comment by darold** [comment]
Might be fixed in coming v8.2 by using fixed length for the div instead of 100% of the parent object.
