### ISSUE TITLE
pgbadger installation

### ISSUE THREAD

**Issue by satyamsaksham** [dalibo/pgbadger#291]
I'm working with Openbravo, I would like to monitor databases [ remotely ] stored in PostgreSQL.

I'd gone through documentation of #[pgBadger](http://dalibo.github.io/pgbadger/) and installed, 
of course that suits to my requirement. But I'm not aware of how can I observe the things I want.

One of my requirement is to find Slowest queries and Optimizing them.

Is there any UI is to be installed ?

**Comment by darold** [comment]
The output of pgbadger is written to file out.html by default, using Firefox or Chrome to read this file you will be able to see a kind of UI. Then goto menu "Top"->"Slowest individual queries" to see your requirement.

Regards,

**Comment by satyamsaksham** [comment]
I couldn't find out.html anywhere in my Machine.

Thank you

**Comment by darold** [comment]
Here is a good howto use pgbadger:  https://www.dhis2.org/analysing-postgresql-logs-using-pgbadger  just replace with newer version.

Note that you can also run pgBadger in incremental mode and saved the reports in an Apache HTML repository, for example /var/www/pgbadger/ . You will be able to browse daily and weekly reports. I can not find any tutorial, but look at options -I and -R .

**Comment by satyamsaksham** [comment]
Thank you very much.

In the place of pg.log I gave /var/log/postgresql/postgresql-9.3-main.log, working fine now.
