### ISSUE TITLE
Remote hosts

### ISSUE THREAD

**Issue by satyamsaksham** [dalibo/pgbadger#292]
Hi,
How to monitor databases of remote hosts ?

**Comment by darold** [comment]
If you are asking how to analyze log remotely with pgbadger, just execute pgbadger with the ip address of the remote server and the path to the log file:

```
    pgbadger --remote-host192.168.1.159  /var/log/postgresql/postgresql-9.3-main.log
```

You need to exchange ssh key between de machine to be able to execute the command without typing a password.

**Comment by satyamsaksham** [comment]
sudo pgbadger --remote-host 192.168.0.105  /var/log/postgresql/postgresql-9.3-main.log
[sudo] password for saksham: 
The authenticity of host '192.168.0.105 (192.168.0.105)' can't be established.
ECDSA key fingerprint is 32:87:18:d7:28:7f:45:92:84:cf:ac:87:bf:74:17:f1.
Are you sure you want to continue connecting (yes/no)? yes
Warning: Permanently added '192.168.0.105' (ECDSA) to the list of known hosts.
Permission denied (publickey,password).
FATAL: you must give a log file as command line parameter.


Usage: pgbadger [options] logfile [...] . . .

**Comment by darold** [comment]
You can not use sudo  to run pgbadger in this use or at least it generate an error that return an empty log file. Here is what you should see:
```
gilles@W230ST:~$ /home/git/pgbadger/pgbadger -f stderr --remote-host 192.168.1.127 /var/log/postgresql/postgresql-9.5-main.log.1
[========================>] Parsed 381531 bytes of 381531 (100.00%), queries: 304, events: 259
```

With this user I'm able to read the log file at remote side. If you need to use a specific user or ssh key, see options --ssh-* You will also have to specify the PostgreSQL log format with the -f option.

**Comment by satyamsaksham** [comment]
saksham@saksham:~$ /home/saksham/Downloads/pgbadger-6.4/pgbadger -f stderr
--remote-host 192.168.0.105 /var/log/postgresql/postgresql-9.3-main.log.1
Permission denied (publickey,password).
FATAL: you must give a log file as command line parameter.


Usage: pgbadger [options] logfile [...]

**Comment by darold** [comment]
Please, you are using an old release, you can download version 8.1 here  https://github.com/dalibo/pgbadger/releases

And check the following command:

    ssh 192.168.0.105 tail /var/log/postgresql/postgresql-9.3-main.log.1

**Comment by satyamsaksham** [comment]
_~$ ssh 192.168.0.100 tail /var/log/postgresql/postgresql-9.3-main.log_ 
saksham@192.168.0.100's password: 
	to_char(co.em_oca_eta) as eta,sum(col.qtyinvoiced) as qty
	from c_order co
	left join c_doctype cdt on cdt.c_doctype_id = co.c_doctypetarget_id
	left join c_bpartner cbp on cbp.c_bpartner_id = co.c_bpartner_id
	left join FIN_Payment_Sched_Ord_V fp on fp.c_order_id = co.c_order_id
	left join c_orderline col on col.c_order_id = co.c_order_id
	left join ad_org org on org.ad_org_id = co.ad_org_id
	where co.issotrx= 'Y'
	group by docnum,docname,docstatus,bpcardcode,bpname,docdate,datedue,eta
	order by docnum
Actual log file has more lines.

**Comment by satyamsaksham** [comment]
$ ssh sysuser@***.***.**.** tail
/var/log/postgresql/postgresql-9.1-main.log.1
sysuser@***.***.**.**'s password:
tail: cannot open ‘/var/log/postgresql/postgresql-9.1-main.log.1’ for
reading: Permission denied

**Comment by satyamsaksham** [comment]
Good Afternoon,

Thank you, Now I'm using pgbadger 8.1. I'm having above error. Pl. help me.

**Comment by satyamsaksham** [comment]
Here are the results when I perform previous commands you suggested :

$ pgbadger --remote-host 192.168.0.100
/var/log/postgresql/postgresql-9.3-main.log
ssh: connect to host 192.168.0.100 port 22: Connection timed out
FATAL: you must give a log file at command line parameter.


$ pgbadger -f stderr --remote-host 192.168.0.100
/var/log/postgresql/postgresql-9.1-main.log.1
ssh: connect to host 192.168.0.100 port 22: Connection timed out
FATAL: you must give a log file at command line parameter.

**Comment by darold** [comment]
You have to perform a ssh key exchange between the machine to be able to connect without password, see ssh-copy-id

**Comment by satyamsaksham** [comment]
I followed this documentation
<https://www.digitalocean.com/community/tutorials/how-to-set-up-ssh-keys--2>
but remote host still asking to enter the password
$ ssh 'user@IP'
user@IP's password:

**Comment by darold** [comment]
Hi,

It seems that what you want to achieve is not whole under control and so in this case I recommend you to not start with remote capabilities of pgbadger and to test again after some training. For the moment you can transfer your logs using ftp or otherwise you can use rsyslog to centralized your log but this last solution can be difficult too if you don't have sysadmin skills.

Best regards,

**Comment by satyamsaksham** [comment]
Hi,

Through sftp I'm able to access remote host and I can transfer that log
file to my machine, generate out.html. Is there any possibility to copy
that log file from the remote system and generate out.html by using
*crontab* ?

**Comment by satyamsaksham** [comment]
Hello #darold <https://github.com/darold>,

Now I'm able to connect with my host and tried this command *ssh User@IP
tail /var/log/postgresql/postgresql-9.1-main.log.1. **; *having last 10
lines of the log file.
Please tell me how can I generate *out.html *periodically.

Thank you.

**Comment by satyamsaksham** [comment]
Hi,

I tried this command and it's generating out.html too, but no content
within.

*./pgbadger -v -f stderr -r 148.251.54.50 --ssh-user citium -b '2014-09-26
04:48:01' -e '2014-09-26 04:54:00'
/var/log/postgresql/postgresql-9.1-main.log.1* [Ref : Issue #197 ]
<https://github.com/dalibo/pgbadger/issues/197>
DEBUG: Looking for remote filename using command: ssh -o ConnectTimeout=10
-o PreferredAuthentications=hostbased,publickey my_user@my_host "ls
/var/log/postgresql/postgresql-9.1-main.log.1"
DEBUG: Output 'html' reports will be written to out.html
DEBUG: Starting to parse remote log file:
my_host:/var/log/postgresql/postgresql-9.1-main.log.1
DEBUG: Looking for file size using command: ssh -o ConnectTimeout=10 -o
PreferredAuthentications=hostbased,publickey my_user@my_host "ls -l
/var/log/postgresql/postgresql-9.1-main.log.1" | awk '{print $5}'
DEBUG: Remote file size: 463989
DEBUG: Retrieving log entries using command: ssh -o ConnectTimeout=10 -o
PreferredAuthentications=hostbased,publickey my_user@my_host " cat
/var/log/postgresql/postgresql-9.1-main.log.1" |
DEBUG: Starting reading file
my_host:/var/log/postgresql/postgresql-9.1-main.log.1...
DEBUG: Looking for file size using command: ssh -o ConnectTimeout=10 -o
PreferredAuthentications=hostbased,publickey my_user@my_host "ls -l
/var/log/postgresql/postgresql-9.1-main.log.1" | awk '{print $5}'
DEBUG: Remote file size: 463989
DEBUG: Retrieving log entries using command: ssh -o ConnectTimeout=10 -o
PreferredAuthentications=hostbased,publickey my_user@my_host " cat
/var/log/postgresql/postgresql-9.1-main.log.1" |
cat: /var/log/postgresql/postgresql-9.1-main.log.1: Permission denied
cat: /var/log/postgresql/postgresql-9.1-main.log.1: Permission denied
DEBUG: Start parsing at offset 0 of file
/var/log/postgresql/postgresql-9.1-main.log.1 to 463989
[>                        ] Parsed      0 bytes of 463989 (0.00%), queries:
0, events: 0
DEBUG: the log statistics gathering took: 6 wallclock secs ( 0.00 usr  0.01
sys +  0.15 cusr  0.02 csys =  0.18 CPU)
*LOG: Ok, generating html report...*
DEBUG: building reports took:  0 wallclock secs ( 0.01 usr +  0.00 sys =
0.01 CPU)
DEBUG: the total execution time took:  6 wallclock secs ( 0.01 usr  0.01
sys +  0.15 cusr  0.02 csys =  0.19 CPU)


Thanks and Warm Regards,

>
>
>

**Comment by darold** [comment]
If you take care of the debug output It might be obvious:
```
cat: /var/log/postgresql/postgresql-9.1-main.log.1: Permission denied
```

**Comment by satyamsaksham** [comment]
Suggest me, What I've to do; Can I change the permissions of the log in my
host ? Or Any modifications in command ?

**Comment by darold** [comment]
Why not use a user that have read permission (postgres) or include your user in the postgres group? Changing the permission to 644 of the log files on the host will also solves the issue but your log files will be readable by anyone that can login to that host.

**Comment by satyamsaksham** [comment]
After Changing the permissions of the log files out.html file *generated
but with no content* ?

**Comment by darold** [comment]
Congratulation, now you might have a log format issue. Take a look at documentation about supported log format and log line prefix.

**Comment by satyamsaksham** [comment]
Thank you, I made following changes in Postgresql configuration file but
not found any information in

*out.html yet.*
log_line_prefix = '%t [%p]: [%l-1] '
log_statement = 'none'
log_min_duration_statement = 0
log_checkpoints = on
log_connections = on
log_disconnections = on
log_lock_waits = on
log_temp_files = 0
log_autovacuum_min_duration = 0

**Comment by satyamsaksham** [comment]
This is what I can see in my Terminal:

DEBUG: Looking for remote filename using command: ssh -o ConnectTimeout=10
-o PreferredAuthentications=hostbased,publickey user@host "ls
/var/log/postgresql/postgresql-9.1-main.log.1"
DEBUG: Output 'html' reports will be written to out.html
DEBUG: Starting to parse remote log file:
host:/var/log/postgresql/postgresql-9.1-main.log.1
DEBUG: Looking for file size using command: ssh -o ConnectTimeout=10 -o
PreferredAuthentications=hostbased,publickey user@host "ls -l
/var/log/postgresql/postgresql-9.1-main.log.1" | awk '{print $5}'
DEBUG: Remote file size: 463989
DEBUG: Retrieving log entries using command: ssh -o ConnectTimeout=10 -o
PreferredAuthentications=hostbased,publickey user@host " cat
/var/log/postgresql/postgresql-9.1-main.log.1" |
DEBUG: Starting reading file
host:/var/log/postgresql/postgresql-9.1-main.log.1...
DEBUG: Looking for file size using command: ssh -o ConnectTimeout=10 -o
PreferredAuthentications=hostbased,publickey user@host "ls -l
/var/log/postgresql/postgresql-9.1-main.log.1" | awk '{print $5}'
DEBUG: Remote file size: 463989
DEBUG: Retrieving log entries using command: ssh -o ConnectTimeout=10 -o
PreferredAuthentications=hostbased,publickey user@host " cat
/var/log/postgresql/postgresql-9.1-main.log.1" |
DEBUG: Start parsing at offset 0 of file
/var/log/postgresql/postgresql-9.1-main.log.1 to 463989
[========================>] Parsed 463989 bytes of 463989 (100.00%),
queries: 0, events: 0
DEBUG: the log statistics gathering took:11 wallclock secs ( 0.06 usr  0.00
sys +  0.17 cusr  0.06 csys =  0.29 CPU)
LOG: Ok, generating html report...
DEBUG: building reports took:  0 wallclock secs ( 0.01 usr +  0.00 sys =
0.01 CPU)
DEBUG: the total execution time took: 11 wallclock secs ( 0.07 usr  0.00
sys +  0.17 cusr  0.06 csys =  0.30 CPU)

**Comment by darold** [comment]
You need to reload your configuration file after those changes:

    SELECT pg_reload_conf();

as postgres user.

**Comment by satyamsaksham** [comment]
I did that too. But still it is not showing any data. My host using
PostgreSQL 9.1. I attached my html file.

**Comment by satyamsaksham** [comment]
Hello Darold,

Feeling Ebullient !!! Finally output file generated with the Information
when I use *postgresql-9.1-main.log*, postgresql-9.1-main.log.1 instead.
Would you please explain Difference between these two logs ?

**Comment by satyamsaksham** [comment]
Would you please explain the Difference between these two logs ?

/var/log/postgresql/postgresql-9.1-main.log   --->  2.6GB
/var/log/postgresql/postgresql-9.1-main.log.1 --> 51.1GB

Which is to be used in order to generate output file ?

**Comment by darold** [comment]
You may want to reduce the number of information logged. What are the values of the following postgresql.conf directives:

* log_min_messages
* log_min_error_statement
* log_min_duration_statement

**Comment by satyamsaksham** [comment]
#log_min_messages = warning

#log_min_error_statement = error

log_min_duration_statement = 0

**Comment by darold** [comment]
You might want to only logged queries with a duration >= 5 seconds for example to limit size of the log output.

* log_min_duration_statement = 5000

**Comment by darold** [comment]
then reload configuration.

**Comment by satyamsaksham** [comment]
Followed your instructions.

Which file provides reliable results

*/var/log/postgresql/postgresql-9.1-main.log* or
*/var/log/postgresql/postgresql-9.1-main.log.1*

**Comment by darold** [comment]
Use /var/log/postgresql/postgresql-9.1-main.log

**Comment by satyamsaksham** [comment]
This one, *pgbadger -j 4 pg_clean.log -d ril16aug -o ril.html -O
/home/satya/pgbadger-8.1 *not generating output of particular given
database.

Under *Top *tab, how to find out Database of the Query when no particular
dB is mentioned ?

**Comment by darold** [comment]
Commit 147cae3 might solves your issue.

**Comment by darshansh** [comment]
> If you are asking how to analyze log remotely with pgbadger, just execute pgbadger with the ip address of the remote server and the path to the log file:
> 
> ```
>     pgbadger --remote-host192.168.1.159  /var/log/postgresql/postgresql-9.3-main.log
> ```
> You need to exchange ssh key between de machine to be able to execute the command without typing a password.

Hi , 
Could you please specify the correct steps for generate the report remotely ? 
I have created two ubuntu VM servers. 
1. One server-1 has postgresql 10 
2. On server -2  I have installed pgbadger (it installed 7.1 version)
3. then generated SSH key on server 2 and run ssh-copy-id command on server-2 to server-1. 
4.I can access server 1 from server 2
5. however when I run pgbadger command as below I got permission error. 
![image](https://user-images.githubusercontent.com/14271741/54607121-98fe2e00-4a73-11e9-9595-9201fc9a99ea.png)

![image](https://user-images.githubusercontent.com/14271741/54607184-c34feb80-4a73-11e9-88c2-bce6db27a198.png)

Thanks, 
Darshan Shah
