### ISSUE TITLE
Unknown line format

### ISSUE THREAD

**Issue by bobspct** [dalibo/pgbadger#296]
I have a problem with parsing, the log format has not changed:
DEBUG: Unknown line format:  [47265-1] < 2016-08-22 03:42:07.132 MSK >LOG:  duration: 0.942 ms  statement: SELECT .....

In postgresql.conf:
log_line_prefix = '< %m > '

From the beginning, everything was good, the log was processed

**Comment by darold** [comment]
What is you log_destination, syslog or stderr?

**Comment by bobspct** [comment]
log_destination = 'syslog'

**Comment by bobspct** [comment]
Problem solved. Do not trim the beginning of the lines in the log when you transfer it through the rsyslog

**Comment by darold** [comment]
You have set an extra space in your log_line_prefix but I can't see it in the log entry, maybe this is the reason of your empty report. Try to use -p '< %m >' in the pgbadger command line and if it not work, please post here a full line of your log file.

**Comment by darold** [comment]
Ok I've not seen your previous post and the closing.
