### ISSUE TITLE
Question incremental

### ISSUE THREAD

**Issue by Greg-13** [dalibo/pgbadger#297]
Bonjour,

I am using PGbadger since a while and everything works well ; this is not an issue, just a question.
Now I would like to use the increment option.

I run a cron job each night and I would like to know if there is a problem with this cron. How can I force the analysis of the missing day ?

For the following case, I missed the August 18th (the 19/20/21/22 of August were done); 

Example : 
[sys@s9 ~]$ pgbadger -s 2 -j 3 -J 2 --retention 4 -prefix '.....' -incremental --outdir /home/sys/test /logs/postgresql-2016-08-18-00:00:00.log
LOG: Ok, generating global index to access incremental reports...

Thank you

Cordialement

**Comment by darold** [comment]
Hi,

A simple way is to create a temporary output directory and run the following pgbadger command:
```
mkdir /tmp/pgbadger-test/
pgbadger -s 2 -j 3 -J 2 -I --noreport -O /tmp/pgbadger-test/ /logs/postgresql-2016-08-18-00:00:00.log
```
move the binary file generated as follow:
```
mv /tmp/pgbadger-test/2016/08/19/*.bin /home/sys/test/2016/08/19/
```
then execute again your incremental command of pgbadger with the --rebuild option to force pgbadger to regenerate all html report in directory where there is binary files.

**Comment by Greg-13** [comment]
Hi, Thank you for your quick answer. 
Yes I can do as you said. 
Cheers
