### ISSUE TITLE
8.2 release timezone issue

### ISSUE THREAD

**Issue by dhancock** [dalibo/pgbadger#302]
All my logging is UTC/GMT but by default pgbadger graphs are showing local time (that is, log entries or 00:01 UTC to 23:59 UTC, but the graphs show from 20:00 to 20:00 (with nothing shown between 20:00 and 00:00). We rotate the log daily.

The only way I've found to fix this is to put "-Z -4" on the command line, but the cron job that does this would need to be changed when we go off of Daylight Savings Time.

pgbadger 8.2 (I don't see the issue on 8.1).

**Comment by darold** [comment]
Please use pgBadger 9.0. About your issue, the main problem is that javascript always use your the timezone of the computer where the report are seen. Unfortunately the only solution is to use the `-Z '-04'` option. To support daylight savings time you can use a dynamic command to get the timezone offset like:
```
pgbadger ... -Z `date +%z | sed 's/..$//'`
```

**Comment by dhancock** [comment]
Understood. Thank you for explaining and for the snippet to avoid a change at DST transitions.
