### ISSUE TITLE
Can't call method "getline" without a package or object reference at /usr/local/bin/pgbadger line 2556.

### ISSUE THREAD

**Issue by yafeishi** [dalibo/pgbadger#306]
pgbadger -f csv  /home/pgsql_data/cn01/pg_log/* --retention 4 -I -q --remote-host host200 -O /home/tools/pgbadger/pgbadger_log

when i use -r param, it run error:
Can't call method "getline" without a package or object reference at /usr/local/bin/pgbadger line 2556.

when not use -r ,it ok

pgBadger version 9.0

**Comment by darold** [comment]
Hi,

Parsing csv file remotely is not permitted. Extracted from documentation:
```
pgBadger can also be used in a central place to parse remote log files using a
passwordless SSH connection. This mode can be used with compressed files and in
the multiprocess per file mode (-J) but can not be used with the CSV log format.
```

Regards
