### ISSUE TITLE
Avg columns are all empty in pgbadger_tools with csv output

### ISSUE THREAD

**Issue by seikoudoku2000** [dalibo/pgbadger#307]
Hi,
thank you very much for providing this great tool.

When I tried `pgbadger_tools` with `--csv-normalized` , values in `Avg` columns in output files are all empty, and maybe because of that, sort itself didn't work properly and meaningless result was there. I mean it looks like random queries are in the output file.
https://github.com/dalibo/pgbadger/blob/master/tools/pgbadger_tools#L1265

my executed command is like this.
```
pgbadger -p '%m [%p]: [%l-1] db=%d,user=%u ' -O /var/tmp -o test.bin postgresql.log
./pgbadger_tools --csv-normalized --csv-filename normalized.csv /var/tmp/test.bin
```
I tried both on version 9.0 and version 8.3, and the same results.

When I executed pgbadger with html as output, it worked perfectly.

My guess is something wrong in the intermediate binary file and `pgbadger_tools` couldn't load average values. But I'm new to both on this tool and perl, and stuck there. 
Please let me know if more information is needed or there exists something I can do by myself.

Thanks,
Yosuke

**Comment by darold** [comment]
Hi,

Please, use latest code from github, last commit 2a11b8f solves this issue.

Regards,

**Comment by seikoudoku2000** [comment]
Thank you very much for the quick fix and confirmed the change resolved the issue.
Closing the issue now.

Best regards,
Yosuke
