### ISSUE TITLE
pgbadger9.0

### ISSUE THREAD

**Issue by Jerryliuk** [dalibo/pgbadger#308]
Hello, 
   I have downloaded and install pgbadger 9.0 and run it against a log file using the following command:
            ./pgbadger -p '%t %c %a user=%u,db=%d,host=%h ' motors.log

   OUTPUT:
            [===================>     ] Parsed 2951833 bytes of 3614691 (81.66%), queries[========================>] Parsed 3614691 bytes of 3614691 (100.00%), queries: 1, events: 0

   However, with pgbadger 8.1, i run the same log file using the following command: 
               ./pgbadger -p '%t %c %a user=%u,db=%d,host=%h ' motors.log

```
Output :      
      [===================>     ] Parsed 2951833 bytes of 3614691 (81.66%), queries[========================>] Parsed 3614691 bytes of 3614691 (100.00%), queries: 4157, events: 4
```

LOG: Ok, generating html report...

```
I have lost information when using pgbadger 9.0. Can you please advice ?
```

thanks
regards
Jerry

**Comment by darold** [comment]
Hi,

Please update to latest development code, commit 3c76328 allow %c (session id) to replace %p (pid) as unique session id like in your prefix.

Regards,
