### ISSUE TITLE
Problema con Pgbadger

### ISSUE THREAD

**Issue by Jimbo69mt** [dalibo/pgbadger#309]
He seguido los pasos que indica la documentación de pgbadger, pero lamentablemente no me carga las consultas para poder analizarlo. Ejecuto el siguiente comando::

[root@localhost ~]# pgbadger   --prefix='%t [%p]: [%l-1] db=%d,user=%u,app=%a,client=%h '   postgresql-20161020.log 
[========================>] Parsed 57961062 bytes of 57961062 (100.00%), **queries: 0,** events: 24
LOG: Ok, generating html report...
[root@localhost ~]# 

Como veran en quieries esta con valor 0, a pesar de que en el archivo lo de postgresql se han realizado muchas consultas sql.

Necesito urgente poder analizar las consultas de este log, alguien puede ayudarme??  @dalibo

**Comment by darold** [comment]
Please post here a line of the postgresql-20161020.log file to see if the prefix really match.

Regards,

**Comment by darold** [comment]
Gracias a añadir una línea del archivo.

**Comment by darold** [comment]
I suppose that this was a prefix issue.
