### ISSUE TITLE
Feature Request: Multiple output files

### ISSUE THREAD

**Issue by gmr** [dalibo/pgbadger#311]
It'd be useful to have an option to split out the top-level sections of the report to individual HTML files instead of a single HTML file.

The reports I am generating are so large they are not fully loading in Chrome (> 100MB+). Splitting them out would allow for quicker access to specific parts of the report when dealing with lots of data.

**Comment by darold** [comment]
Usually pgbadger report are around 10Mb - 15Mb maximum, if your report reach 100MB maybe you are not using the right prefix, or you are storing too much top queries and the last cause would be very long queries.
What is the value of `-t` or `--top` option? If your queries are really too big, you can use `--maxlength` to limit their size in the report.

**Comment by gmr** [comment]
I'm using the defaults on both. I'lll try with --maxlength.
