### ISSUE TITLE
Support for reading logs from journald

### ISSUE THREAD

**Issue by martonsz** [dalibo/pgbadger#315]
I am running PostgreSQL in a Docker container where I am using the journald log driver.
Is it possible to support reading the logs from the journald?

search_tags: journald journalctl docker

**Comment by darold** [comment]
Hi,

That should be the case, pgbadger supports journald through the following command for example:

    pgbadger --journalctl 'journalctl -u postgresql-9.5'

Using `--journalctl` you can specify the journalctl you want.

**Comment by martonsz** [comment]
Oh sorry. I did not see the --journalctl parameter on the first page >_<
I thought I searched the repository for the word "journalctl". But I must have only searched for "journald" :(
You can delete this Issue if you want...

Thank you for a greate software! 👍 😸

**Comment by darold** [comment]
No problem, please report any issue or feature request about journald use by pgbadger, this feature has not been heavily used, at least by me, and perhaps it might be improved.
