### ISSUE TITLE
--log-duration doesn't work?

### ISSUE THREAD

**Issue by ericcj** [dalibo/pgbadger#316]
I'm using RDS with log_statement=all, log_duration=on and log_min_duration_statement=300ms.  I realize this isn't recommended but I don't want to reboot my instance to fix it.  I'm running pgbadger --prefix '%t:%r:%u@%d:[%p]:' --log-duration postgresql.log.2016-12-06-15.  But my report ends up having durations for the "Histogram of query times" section but seemingly not associated for the "Slowest individual queries" and others:

![screen shot 2016-12-06 at 11 34 52 am](https://cloud.githubusercontent.com/assets/53106/20934594/b5a75820-bba9-11e6-9153-78f06d2e9efa.png)

It sounds like --log-duration is meant to work with this configuration, but specifying it seems to have no effect on that Queries tab (although it does also break the Overview tab timestamp parsing by lumping all the queries into the same second:  "2016-12-06 15::").

This sounds similar to https://github.com/dalibo/pgbadger/issues/274

**Comment by darold** [comment]
Hi,

You don't need to reboot your instance to apply the configuration change required by pgbadger, a reload is enough. If you want to be able to parse your log as it is expected to work with your command line, please download latest code from gihtub, last commit 9fe6b00 fixes this issue. Thanks for the report.

Regards,

**Comment by ericcj** [comment]
awesome, the "Top" tab with --log-duration is indeed fixed in master, many thanks. it does appear to still break the date parsing somehow on the overview tab, which works fine without --log-duration:

![screen shot 2016-12-06 at 2 25 17 pm](https://cloud.githubusercontent.com/assets/53106/20940345/6b6a0f2a-bbc0-11e6-97fe-07ce6f48b48c.png)


it doesn't appear that there's a way to reload on amazon RDS postgresql without a restart.

**Comment by ericcj** [comment]
actually i'm wrong, master doesn't have a working overview tab for me with or without --log-duration.  pgbadger 9.0 has a working overview tab only if i do not specify --log-duration

**Comment by darold** [comment]
Please retrieve latest code, commit bcc94b2 might solve date report.

**Comment by ericcj** [comment]
yup, now both screens work with --log-duration and overview works even without it.  THANKS
