### ISSUE TITLE
Issue with using --pgbouncer-only

### ISSUE THREAD

**Issue by clomdd** [dalibo/pgbadger#317]
When I try to use pgBadger to parse a pgBouncer logfile I get 0 events reported and the html page has no links, only a logo and a stripey grey background. I'm not sure whether I'm misusing the --pgbouncer-only flag and haven't got another option I need or if there's a problem with the code. Please could you offer me an example of how to run pgbadger on a pgbouncer logfile. I am currently using version 8.2, I've just checked though and it does the same with version 9.

Thanks!

**Comment by darold** [comment]
Please use latest codfe from github this issue might have been fixed. Also this is normal that the progress bar show 0 query, there's no queries in pgbouncer log. If you still have the issue, please send me a part of your log. This week I've parsed successfully a 2GB pgbouncer log with --pgbouncer-only so it might works for you.

**Comment by clomdd** [comment]
We overlapped, thanks for your quick reply. I was just updating to say that I've tested with version 9 and I get the same issue. I am expecting the below to report as an event. Even if it is picking up no events I'd expect the html page to display the menus as with the postgres log parsing, but it doesn't.

2016-12-07 13:09:35.846 78784 LOG S-0xe53d98: database2/user@127.0.0.1:5111 new connection to server (from 127.0.0.1:33242)
2016-12-07 13:09:35.848 78784 ERROR S: login failed: FATAL: too many connections for role "user"
2016-12-07 13:09:35.848 78784 LOG S-0xe53d98: database2/user@127.0.0.1:5111 closing because: login failed (age=0)
2016-12-07 13:10:04.179 78784 LOG S-0xe53d98: database2/user@127.0.0.1:5111 new connection to server (from 127.0.0.1:33246)
2016-12-07 13:10:04.180 78784 ERROR S: login failed: FATAL: too many connections for role "user"
2016-12-07 13:10:04.180 78784 LOG S-0xe53d98: database2/user@127.0.0.1:5111 closing because: login failed (age=0)
2016-12-07 13:10:30.372 78784 LOG Stats: 0 req/s, in 0 b/s, out 1 b/s,query 26890137 us
2016-12-07 13:11:20.682 78784 LOG C-0xe4ec50: database2/user@127.0.0.1:57192 closing because: client close request (age=204)
2016-12-07 13:11:30.372 78784 LOG Stats: 0 req/s, in 0 b/s, out 0 b/s,query 0 us

**Comment by clomdd** [comment]
I was trying to run it with the remote processing option on, which we use when processing our database log files. Having removed this it now works. Are the two not compatible intentionally?

**Comment by darold** [comment]
Things works as expected for me using your sample log and the following pgbadger command:
```
$ perl pgbadger -v -r 192.168.1.100 --ssh-user postgres -f pgbouncer --pgbouncer-only log_pgbouncer.log
```
Here is the debug ooutput:

```
DEBUG: Looking for remote filename using command: ssh -o ConnectTimeout=10 -o PreferredAuthentications=hostbased,publickey postgres@10.18.1.100 "ls log_pgbouncer.log"
DEBUG: Output 'html' reports will be written to out.html
DEBUG: Can not autodetect log format, assuming pgbouncer.
DEBUG: Starting to parse remote log file: 10.18.1.100:log_pgbouncer.log
DEBUG: Looking for file size using command: ssh -o ConnectTimeout=10 -o PreferredAuthentications=hostbased,publickey postgres@10.18.1.100 "ls -l log_pgbouncer.log" | awk '{print $5}'
DEBUG: Remote file size: 964
DEBUG: Retrieving log entries using command: ssh -o ConnectTimeout=10 -o PreferredAuthentications=hostbased,publickey postgres@10.18.1.100 " cat log_pgbouncer.log" |
DEBUG: Starting reading file 10.18.1.100:log_pgbouncer.log...
DEBUG: Start parsing at offset 0 of file log_pgbouncer.log to 964
[========================>] Parsed 964 bytes of 964 (100.00%), queries: 0, events: 2
DEBUG: the log statistics gathering took: 1 wallclock secs ( 0.00 usr  0.00 sys +  0.01 cusr  0.00 csys =  0.01 CPU)
LOG: Ok, generating html report...
DEBUG: building reports took:  0 wallclock secs ( 0.00 usr +  0.00 sys =  0.00 CPU)
DEBUG: the total execution time took:  1 wallclock secs ( 0.00 usr  0.00 sys +  0.01 cusr  0.00 csys =  0.01 CPU)
```

Note that you must specify the log format.

**Comment by clomdd** [comment]
I hadn't picked up that the format needed to be listed as pgbouncer. That's not actually mentioned as an option in the docs. I read somewhere that it's now possible to process pgbouncer and postgres files into the same file, what is the syntax for that?

Thanks for your swift help!

**Comment by darold** [comment]
No you can't process pgbouncer and postgres log entries from the same file because pgbadger can only parse a log format at once. But you can give two log files to parse, one coming from pgbouncer and the other from PostgreSQL, at the same time.

I will mention the pgbouncer log format in the doc.

**Comment by darold** [comment]
Just done it in commit 4d951e5.

**Comment by clomdd** [comment]
Thank you very much for your help.
