### ISSUE TITLE
Global index calendar background breaks up on browser resize

### ISSUE THREAD

**Issue by clomdd** [dalibo/pgbadger#318]
When I have my Chrome or Firefox session maximised on the global index page the background window behind each calendar month turns into a panel running along the left of the month, only being a background for the first letter or two of the month name rather than appearing as a background behind the whole month. In Internet Explorer the background stays but instead the months stretch out. I think there's an issue with the css. Everything is still working, it's just less pretty, so this isn't urgent.

Thanks!

**Comment by darold** [comment]
Commit ceafe47 fix this issue.
