### ISSUE TITLE
Second weekly report not correct

### ISSUE THREAD

**Issue by birkosan** [dalibo/pgbadger#322]
Hi

I use pgbadger like this:

pgbadger --average 1 \
                --sample 15 \
                --top 50 \
                --start-monday \
                -v \
                -I \
                -J 4 \
                -O /var/www/html \
                --format syslog pgbouncer.log --format stderr pgsql.log.gz

The first weekly report include only tha day 2017-01-01 ... thats ok ... but the second starting at 2017-01-01 too.
The third weekly report start at 2017-01-09 which is ok.
So practically the day of 2017-01-08 is missing from all weekly reports (the daily is ok)

Thank you for your work
Levi

**Comment by darold** [comment]
I'm not able to reproduce the issue, can you post here the result of the following commands:
```
ls -la  /var/www/html/2016/
ls -la  /var/www/html/2017/
```
Regards,

**Comment by birkosan** [comment]
# ls -la  /var/www/html/2016/
total 52
drwxr-xr-x 67 root root 4096 Jan  3 13:42 .
drwxr-xr-x  5 root root   71 Jan 26 02:01 ..
drwxr-xr-x 33 root root 4096 Oct  4 09:55 01
drwxr-xr-x 31 root root 4096 Oct  4 11:18 02
drwxr-xr-x 33 root root 4096 Oct  4 13:16 03
drwxr-xr-x 32 root root 4096 Oct  4 14:52 04
drwxr-xr-x 33 root root 4096 Oct  4 16:32 05
drwxr-xr-x 32 root root 4096 Oct  4 18:07 06
drwxr-xr-x 33 root root 4096 Oct  4 19:39 07
drwxr-xr-x 33 root root 4096 Oct  4 21:19 08
drwxr-xr-x 32 root root 4096 Oct  5 10:44 09
drwxr-xr-x 33 root root 4096 Oct 31 02:00 10
drwxr-xr-x 32 root root 4096 Dec  7 11:08 11
drwxr-xr-x 33 root root 4096 Jan  3 14:04 12
drwxr-xr-x  2 root root   23 Oct  4 08:37 week-01
drwxr-xr-x  2 root root   23 Oct  4 08:42 week-02
drwxr-xr-x  2 root root   23 Oct  4 09:04 week-03
drwxr-xr-x  2 root root   23 Oct  4 09:23 week-04
drwxr-xr-x  2 root root   23 Oct  4 09:42 week-05
drwxr-xr-x  2 root root   23 Oct  4 10:00 week-06
drwxr-xr-x  2 root root   23 Oct  4 10:20 week-07
drwxr-xr-x  2 root root   23 Oct  4 10:40 week-08
drwxr-xr-x  2 root root   23 Oct  4 10:59 week-09
drwxr-xr-x  2 root root   23 Oct  4 11:21 week-10
drwxr-xr-x  2 root root   23 Oct  4 12:07 week-11
drwxr-xr-x  2 root root   23 Oct  4 12:29 week-12
drwxr-xr-x  2 root root   23 Oct  4 12:50 week-13
drwxr-xr-x  2 root root   23 Oct  4 13:11 week-14
drwxr-xr-x  2 root root   23 Oct  4 13:32 week-15
drwxr-xr-x  2 root root   23 Oct  4 13:54 week-16
drwxr-xr-x  2 root root   23 Oct  4 14:16 week-17
drwxr-xr-x  2 root root   23 Oct  4 14:39 week-18
drwxr-xr-x  2 root root   23 Oct  4 14:59 week-19
drwxr-xr-x  2 root root   23 Oct  4 15:22 week-20
drwxr-xr-x  2 root root   23 Oct  4 15:46 week-21
drwxr-xr-x  2 root root   23 Oct  4 16:09 week-22
drwxr-xr-x  2 root root   23 Oct  4 16:32 week-23
drwxr-xr-x  2 root root   23 Oct  4 16:54 week-24
drwxr-xr-x  2 root root   23 Oct  4 17:16 week-25
drwxr-xr-x  2 root root   23 Oct  4 17:38 week-26
drwxr-xr-x  2 root root   23 Oct  4 18:01 week-27
drwxr-xr-x  2 root root   23 Oct  4 18:24 week-28
drwxr-xr-x  2 root root   23 Oct  4 18:41 week-29
drwxr-xr-x  2 root root   23 Oct  4 19:03 week-30
drwxr-xr-x  2 root root   23 Oct  4 19:25 week-31
drwxr-xr-x  2 root root   23 Oct  4 19:45 week-32
drwxr-xr-x  2 root root   23 Oct  4 20:08 week-33
drwxr-xr-x  2 root root   23 Oct  4 20:31 week-34
drwxr-xr-x  2 root root   23 Oct  4 20:54 week-35
drwxr-xr-x  2 root root   23 Oct  4 21:16 week-36
drwxr-xr-x  2 root root   23 Oct  5 09:26 week-37
drwxr-xr-x  2 root root   23 Oct  5 09:48 week-38
drwxr-xr-x  2 root root   23 Oct  5 10:10 week-39
drwxr-xr-x  2 root root   23 Oct  5 10:45 week-40
drwxr-xr-x  2 root root   23 Oct  5 10:46 week-41
drwxr-xr-x  2 root root   23 Oct 10 02:03 week-42
drwxr-xr-x  2 root root   23 Oct 17 02:03 week-43
drwxr-xr-x  2 root root   23 Oct 24 02:03 week-44
drwxr-xr-x  2 root root   23 Oct 31 02:03 week-45
drwxr-xr-x  2 root root   23 Nov  7 02:03 week-46
drwxr-xr-x  2 root root   23 Nov 14 02:03 week-47
drwxr-xr-x  2 root root   23 Dec  7 10:45 week-48
drwxr-xr-x  2 root root   23 Dec  7 11:05 week-49
drwxr-xr-x  2 root root   23 Dec  7 11:35 week-50
drwxr-xr-x  2 root root   23 Dec 12 02:03 week-51
drwxr-xr-x  2 root root   23 Dec 19 02:06 week-52
drwxr-xr-x  2 root root   23 Jan  3 13:42 week-53


# ls -la  /var/www/html/2017/
total 4
drwxr-xr-x  8 root root   85 Jan 23 02:04 .
drwxr-xr-x  5 root root   71 Jan 26 02:01 ..
drwxr-xr-x 28 root root 4096 Jan 26 02:00 01
drwxr-xr-x  2 root root   23 Jan  3 14:15 week-01
drwxr-xr-x  2 root root   23 Jan  3 14:22 week-02
drwxr-xr-x  2 root root   23 Jan  9 02:03 week-03
drwxr-xr-x  2 root root   23 Jan 16 02:05 week-04
drwxr-xr-x  2 root root   23 Jan 23 02:04 week-05

**Comment by darold** [comment]
I'm closing it because I can't reproduce the problem.
