### ISSUE TITLE
Multiple appname Values

### ISSUE THREAD

**Issue by mikealbert** [dalibo/pgbadger#323]
Hi,

I was wondering if there is a way to pass in multiple appname values.  As an example, we have multiple instances of puma app servers such as:

```
puma: cluster worker 0: 12 [webapp]
puma: cluster worker 0: 13 [webapp]
puma: cluster worker 1: 12 [webapp]
puma: cluster worker 1: 13 [webapp]
```

I'd like to generate a pgbadger report that incudes all instances of puma, but excludes several other database connections.

**Comment by darold** [comment]
Hi,

If I understand well, you just have to use multiple time the `--appname=x` option at command line, or if you prefer you can use multiple `--exclude-appname=x` to not report logs related to the given apps. Is that what you were looking for?

**Comment by mikealbert** [comment]
Yep.  That's exactly what I was looking for.  I had tried passing in a regex or comma separated list, but couldn't figure out why it wasn't working.

Thanks!
