### ISSUE TITLE
Readme is very hard to read.

### ISSUE THREAD

**Issue by ipepe** [dalibo/pgbadger#325]
English is second language for me, so using pain simple sentences would be nice. I barely understand what is written in readme. Especially section about configuring postgres, it's a mess. It would be easier and simpler if You could paste Your example config.

Also my remarks here:
```
pgBadger is a PostgreSQL log analyzer built for speed with fully reports
    from your PostgreSQL log file
```
fully? fully what? reports? fully incomprehensible

```
 Of course your log messages should be in English without locale support:

            lc_messages='C'

    but this is not only recommended by pgBadger.
```
Not only recommended? What an actual WHAT? Not recommended? Only recommended? What is message behind this sentence?

**Comment by darold** [comment]
Hi,

I'm sorry but English is a second language for me too, so I think this is the best I can produce or at least the more comprehensible. Patches on documentation are welcome.

Regards,
