### ISSUE TITLE
"Overview Section" some reports not properly feed with auto_explain.log_min_duration=0 on and log_min_duration_statement=-1

### ISSUE THREAD

**Issue by jacks33** [dalibo/pgbadger#326]
Hello,

Full settings are on the bottom of the ticket.

This case is most related to two parameters : 
log_min_duration_statement = -1
and 
auto_explain.log_min_duration = 0

With these settings reports on "Top" section are correctly displayed:

Most of over reports in "Overview, section" doen't take in account SELECT and DML statements while section "Top" take then in account.

This is a pity because it requires both log_min_duration_statement and  auto_explain.log_min_duration to be set.

Its' consequence is query text are written twice in logs (one for log_min_duration_statement  and one for auto_explain.log_min_duration(with explain as well).

Status of reports:

report "Global stats" seems ok.
report "SQL traffic", "General Activity" and "Queries duration" doesn't take in account SELECT and DML statements.
reports "Select traffic" and "INSERT/UPDATE/DELETE Traffic" are empty.

Full Settings:

lc_messages = 'C'
log_destination = 'stderr'
logging_collector = on
log_filename = 'postgresql-%Y%m%d_%H%M.log'
log_truncate_on_rotation = 1d
log_rotation_age = 1d
log_rotation_size = 0

#client_min_messages = notice
#log_min_messages = warning
#log_min_error_statement = error
log_min_duration_statement = -1

log_checkpoints = off
log_connections = off
log_disconnections = off
#log_duration = off
#log_error_verbosity = default
#log_hostname = off
log_line_prefix = '%t [%p]: [%l-1] user=%u,db=%d,app=%a,xid=%x,sqlstate=%e,client=%h '
log_lock_waits = on
log_statement = 'ddl'
#log_replication_commands = off
log_temp_files = 0

log_autovacuum_min_duration = 0

auto_explain.log_min_duration = '0'
auto_explain.log_analyze = on

Thank you.

**Comment by darold** [comment]
I'm not able to reproduce the problem even with the same parameters. You may want to use latest development code an issue on auto_explain parsing was fixed some weeks ago.

**Comment by jacks33** [comment]
with release pgbadger-9.1-1.rhel7.noarch.rpm
(Note I  use the option --anonymize)

here is the command line :
pgbadger -p '%t [%p]: [%l-1] user=%u,db=%d,app=%a,xid=%x,sqlstate=%e,client=%h ' --anonymize  --top 40  --jobs 4 --dns-resolv -o name5.html -f stderr postgres....log

I issued 2 queries : 1 insert and 1 select

For the insert it is fixed: write appears in all reports

For the select I had an issue but it seems a different one:

On "Top" section:
Histogram report ok: (2 queries).
All other reports:
"Slowest individual queries", "Time consuming queries","Most frequent query","Normalized slowest queries : nok (only reports one query, the "insert" one)

On section "Overview":

"Global stats" report: 
number of unique normalized queries =1 => nok (should be 2)  
Number of queries  =2 ,=> ok 
Total query duration 0 (maybe because both queries <1ms)
..

"SQL traffic"
on graph => nok (only one querie miss select)

"SELECT traffic" 
nok => 0 queries instead of 1

"INSERT traffic "
1 query" => ok

"queries duration"
ok => "see two graphs"
 
"prepared queries ratios"
not checked

"general activity" section
queries => ok
Read queries=> nok 0 instead of one.
Write queries => ok.

"Queries" section
Total read queries => nok (0 instead of 1) as  well as on chart and Table.
On the others sections have the same issu(total request ok, but always missing on chart and Table).


==================
==> After further tests it seems this appears because the SELECT query is the last log of the file, because when I add another "SELECT query"  all perfectly, increments by one, but still miss last statement.
==============

I have 2 points about anonymization on "Top" Section (I don't know if it is a bug):
on "slowest individual queries" report  I have 
INSERT INTO rt VALUES ('ZOmE4E9mhj')
and
SELECT * FROM rt LIMIT 10; 

on the others reports queries appears as:
INSERT INTO rt VALUES (''); 
and 
SELECT * FROM rt LIMIT 0; 


Here are my logs (sorry for the text size I don't fize how to change it):

2017-01-25 16:10:03 CET [8008]: [1-1] user=,db=,app=,xid=0,sqlstate=00000,client= LOG:  database system was shut down at 2017-01-25 16:10:01 CET
2017-01-25 16:10:03 CET [8008]: [2-1] user=,db=,app=,xid=0,sqlstate=00000,client= LOG:  MultiXact member wraparound protections are now enabled
2017-01-25 16:10:03 CET [7961]: [4-1] user=,db=,app=,xid=0,sqlstate=00000,client= LOG:  database system is ready to accept connections
2017-01-25 16:10:03 CET [8012]: [1-1] user=,db=,app=,xid=0,sqlstate=00000,client= LOG:  autovacuum launcher started
2017-01-25 16:21:43 CET [7961]: [5-1] user=,db=,app=,xid=0,sqlstate=00000,client= LOG:  received SIGHUP, reloading configuration files
2017-01-25 16:23:16 CET [7961]: [6-1] user=,db=,app=,xid=0,sqlstate=00000,client= LOG:  received SIGHUP, reloading configuration files
2017-01-25 16:23:49 CET [7961]: [7-1] user=,db=,app=,xid=0,sqlstate=00000,client= LOG:  received SIGHUP, reloading configuration files
2017-01-25 16:23:49 CET [7961]: [8-1] user=,db=,app=,xid=0,sqlstate=00000,client= LOG:  parameter "auto_explain.log_min_duration" changed to "0s"
2017-01-25 16:23:52 CET [28787]: [1-1] user=dbamyinst2,db=first_db2,app=psql,xid=1905,sqlstate=00000,client=[local] LOG:  duration: 0.480 ms  plan:
         Query Text: insert into rt values ('xxxxx');
         Insert on myinst2adm.rt  (cost=0.00..0.01 rows=1 width=0) (actual time=0.480..0.480 rows=0 loops=1)
           Buffers: shared hit=4 read=1 dirtied=1
           ->  Result  (cost=0.00..0.01 rows=1 width=0) (actual time=0.001..0.002 rows=1 loops=1)
                 Output: 'xxxxx'::text
 2017-01-25 16:25:06 CET [29263]: [1-1] user=dbamyinst2,db=first_db2,app=psql,xid=0,sqlstate=00000,client=[local] LOG:  duration: 0.063 ms  plan:
         Query Text: select * from rt limit 10;
         Limit  (cost=0.00..0.22 rows=10 width=5) (actual time=0.028..0.031 rows=10 loops=1)
           Output: t
           Buffers: shared read=1
           ->  Seq Scan on myinst2adm.rt  (cost=0.00..337.65 rows=15165 width=5) (actual time=0.024..0.026 rows=10 loops=1)
                 Output: t
                 Buffers: shared read=1


Thank you very much

**Comment by darold** [comment]
The problem here is that you need to enable log_min_duration_statement too otherwise query are not extracted from plan. A plan need to be associated to a query printed in log from the  log_min_duration_statement configuration directive.

About the anonymized queries without the parameter, this is normal, those queries are normalized.
