### ISSUE TITLE
[Improvement] use SQLSTATE in "Most Frequent Errors/Events" report.

### ISSUE THREAD

**Issue by jacks33** [dalibo/pgbadger#327]
Hi,

When %e set on log_line_prefix parameter.

It could be a good idea to classify Errors with sqlstate as well.

Thanks.

**Comment by darold** [comment]
Commit da4a176 adds a new report "Error class distribution". Thanks for the feature request.

**Comment by jacks33** [comment]
checked with pgbadger-9.1-1.rhel7.noarch.rpm. Display chart and table seemsok.

Thank for the improvement
