### ISSUE TITLE
cancel query doesn't appear in report

### ISSUE THREAD

**Issue by jacks33** [dalibo/pgbadger#328]
Hello,

on section "Queries" -> report "Number of cancelled queries" it seems it doesn't report my cancelled queries:

What I do is:

1 - Launch query : insert into rt select * from generate_series(1,100000000)::text
2 - ctrl-c (to cancel the query)

log file content :
2017-01-20 16:47:01  .....  STATEMENT:  insert into rt select * from generate_series(1,100000000)::text;
243 2017-01-20 .....  LOG:  connection received: host=99.200.xx.xxx port=57829
2017-01-20 16:47:09 CET [25320]: [31-1] .......  ERROR:  canceling statement due to user request

pgbadger doesn't report it.

Do you have an idea ?

Thank you.

**Comment by darold** [comment]
This report doesn't concern statement killed by a user, you will see this statement in the Event/Error report.

**Comment by jacks33** [comment]
ok :)
By the way what kind of queries does this handle, the one killed by postgres , using per example pg_cancel_backend ?

Thank you

**Comment by darold** [comment]
This report concern statement cancelled due to a timeout. It receive data when a line with "canceling statement due to statement timeout" is found in the log. This allow you to detect and count queries that was interrupted by your setting of statement_timeout configuration directive for example.
