### ISSUE TITLE
Adding pgbouncer data into reports blanks postgreslog data

### ISSUE THREAD

**Issue by clomdd** [dalibo/pgbadger#330]
Hi,

I am trying to run pgbadger in incremental mode parsing both postgresql.log.xz files into the same reports as pgbouncer logs.

When I run this some of the reports include the pgbouncer data but blank out all of the postgres data so no records are shown. The weekly reports seems to be most prone, but other daily reports have had the same issue too.

Should this work or is this expected behaviour and not supported?

eg commands:
pgbadger -p "%t:%r:%u@%d:[%p]: " -f stderr -r servername /location/postgresql-${date}.log.xz -O /other_location/pgbadger_reports_new -t 30 --exclude-appname pg_dump -I -X

pgbadger -f pgbouncer -r servername /anotherlocation/pgb_${date} -O /other_location/pgbadger_reports_new -t 30 -I -X -b "${rangedate} 00:00:00" -e "${rangedate} 23:59:59"

Thanks,
Chloe

**Comment by darold** [comment]
Hi,

No this won't work and the result is what you have. To achieve what you want to do you just have to run a single pgbadger command:
```
pgbadger -p "%t:%r:%u@%d:[%p]: " -f stderr -r servername -O /other_location/pgbadger_reports_new \
                -t 30 --exclude-appname pg_dump -I -X \
                /location/postgresql-${date}.log.xz  /anotherlocation/pgb_${date}
```
pgbadger can parse postgresql and pgbouncer together and in incremental mode it will not duplicate statistics from previous run.

**Comment by clomdd** [comment]
Thanks for your quick reply.

I will try doing it this way instead!

Thanks,
Chloe

**Comment by clomdd** [comment]
I've just tried the fix you suggested and it is now not putting the pgbouncer tab in any of the reports at all...any other thoughts?

Thanks!

**Comment by darold** [comment]
What is the content of the LAST_PARSED file?

**Comment by clomdd** [comment]
Apologies for the delay, I have been away.

The LAST_PARSED file has only the postgres entry, and no pgbadger entry.

2015-10-05 23:59:52 5736551 2015-10-05 23:59:52 GMT: Last postgres log entry   (I would like to generate historical reports for comparison purposes which is why the date is so long ago).

Thanks.

**Comment by darold** [comment]
No matter the date in the LAST_PARSED file, if the date on your logs (postresql and pgbouncer) are greater than this date at offset 5736551, the log will be parsed. If your logs have olders entries they will not be parsed. If it don't work and you  know that all entries from the log are newer than the date in the LAST_PARSE file, you can safely remove this file and rerun pgbadger.

**Comment by clomdd** [comment]
Shouldn't there also be a pgbouncer row in the LAST_PARSED file? I am starting in an empty directory when running this test so the LAST_PARSED file is being created fresh, and doesn't include a date for the pgbouncer log despite me passing in one each of a postgres log and a pgbouncer log. I don't think removing the LAST_PARSED file will help.

**Comment by darold** [comment]
Yes, there must be a pgbouncer entry in the LAST_PARSED file. It seems that remote parsing doesn't saved the state of the pgbouncer parsing. Thanks for the report.

**Comment by darold** [comment]
Last commit 7db310c allow remote parsing of pgbouncer and postgresql log files in incremental mode by auto-detecting log format on remote file. You will have an entry for pgbouncer log file into the LAST_PARSED file.

**Comment by clomdd** [comment]
This works when dealing with a file which also exists locally, but when the file only exists on the remote server the following error is thrown:
FATAL: when looking for log file format, can't open file <filename>, No such file or directory

I think it's checking that the file exists locally.

Thanks,
Chloe

**Comment by darold** [comment]
That's right, I forgot to reserve test on binary format on local file only. Last commits fix this issue.

Thanks for the report.

**Comment by clomdd** [comment]
Thanks, this seems to be working now!
