### ISSUE TITLE
Request: Allow removal of statement information at runtime

### ISSUE THREAD

**Issue by jamessewell** [dalibo/pgbadger#331]
Hello,

The major difference between a logfile used by PGBadger and a logfile not used by PGBadger is statement level logging - which can get big.

It would be nice if when run in incremental mode PGBadger could remove the statement information from a log, leaving it as an error log.

Cheers,
James

**Comment by darold** [comment]
Hi,

I don't think this is the role of pgbadger but what you can do is call grep after the call to pgbadger if you want to "clear" your log file.

Regards,
