### ISSUE TITLE
pgbadger shows 0 queries when parsing, but the reports has querys in it

### ISSUE THREAD

**Issue by dudleyperkins** [dalibo/pgbadger#332]
Hello,

i'm using pgbadger from the postgresql-repository, version is 9.0-1.pgdg80+1.

On our new server the reports are working, just like on the other servers, but with a little difference. The output of the commandline-call always states there were 0 queries and events parsed, when in fact there are queries in it and they end up in the report.

Here's what i did to investigate. The "postgresql-9.6-main.log" has only entries for 2.Feb (6:25)-3.Feb (6:25):

```
root@host:~# mkdir /var/www/apache/admin/pgbadger/test
root@host:~# /usr/bin/pgbadger -j 6 -R 5 -I --prefix '%t [%p]: [%l] user=%u,db=%d,app=%a ' /daten/pg_log/db-master/postgresql-9.6-main.log -O /var/www/apache/admin/pgbadger/test/
[========================>] Parsed 1432638 bytes of 1432638 (100.00%), queries: 0, events: 0
LOG: Ok, generating HTML daily report into /var/www/apache/admin/pgbadger/test//2017/02/02/...
LOG: Ok, generating HTML daily report into /var/www/apache/admin/pgbadger/test//2017/02/03/...
LOG: Ok, generating HTML weekly report into /var/www/apache/admin/pgbadger/test//2017/week-06/...
LOG: Ok, generating global index to access incremental reports...
```

So these reports are freshly generated and i would expect them to be empty. But they are not, when i visit "../test/2017/02/02/index.html" it says "87 Number of queries" and "53 Number of events".

Or does pgbadger only show the count of the queries/events that happened on the same day it is run? Because in the logfile there are no queries/events for the 3.Feb (today).

**Comment by darold** [comment]
Please use pgbadger 9.1 this issue might have been fixed and let me know if you still have the same issue.

**Comment by dudleyperkins** [comment]
Ah could've thought of that myself, but this doesn't work either. I took the current pgbadger-script and it still looks the same:

```
root@host:~# /root/pgbadger --version
pgBadger version 9.1

root@host:~# rm -fR /var/www/apache/admin/pgbadger/test/*
root@host:~# /root/pgbadger -j 6 -R 5 -I --prefix '%t [%p]: [%l] user=%u,db=%d,app=%a ' /daten/pg_log/db-master/postgresql-9.6-main.log -O /var/www/apache/admin/pgbadger/test/
[========================>] Parsed 1432638 bytes of 1432638 (100.00%), queries: 0, events: 0
LOG: Ok, generating HTML daily report into /var/www/apache/admin/pgbadger/test//2017/02/02/...
LOG: Ok, generating HTML daily report into /var/www/apache/admin/pgbadger/test//2017/02/03/...
LOG: Ok, generating HTML weekly report into /var/www/apache/admin/pgbadger/test//2017/week-06/...
LOG: Ok, generating global index to access incremental reports...
```

**Comment by darold** [comment]
Ok, sorry I've missed an important comment in your first note:

> Or does pgbadger only show the count of the queries/events that happened on the same day it is run? Because in the logfile there are no queries/events for the 3.Feb (today).

Yes, in incremental mode pgbadger will only parse log line newly created after the previous run of pgbadger, so if you don't have any query log in the day the counter will be 0.

I've tested pgbadger in the same condition as you've reported and it works perfectly.

Regards,

**Comment by dudleyperkins** [comment]
To make sure there were no previous i deleted the test-directory before calling pgbadger. But indeed i think the incremental mode is my problem.

After playing around a little bit, i think i can confirm that the values mentioned on the first line after calling pgbadger refer only to the last day generated !?

My test-log-file has entries for both the 2nd and 3rd of February, but only a few checkpoint lines for the 3rd. As stated above the commandline returns:
```
[========================>] Parsed 1432638 bytes of 1432638 (100.00%), queries: 0, events: 0
LOG: Ok, generating HTML daily report into /var/www/apache/admin/pgbadger/test//2017/02/02/...
LOG: Ok, generating HTML daily report into /var/www/apache/admin/pgbadger/test//2017/02/03/...
LOG: Ok, generating HTML weekly report into /var/www/apache/admin/pgbadger/test//2017/week-06/...
LOG: Ok, generating global index to access incremental reports...
```
Now if i remove the lines from the log for the 3rd, the result is:
```
[========================>] Parsed 1431827 bytes of 1431827 (100.00%), queries: 42, events: 8
LOG: Ok, generating HTML daily report into /var/www/apache/admin/pgbadger/test//2017/02/02/...
LOG: Ok, generating HTML weekly report into /var/www/apache/admin/pgbadger/test//2017/week-06/...
LOG: Ok, generating global index to access incremental reports...
```
If this is how it's supposed to work, i'll find a way to make the output suitable for me. I just misinterpreted the output from pgbadger, i thought it shows the count of all parsed queries in the log-file.

Just to let you know why i'm wondering about this: I am monitoring the amount of queries that gets parsed from pgbadger. Seeing a "0" would make me wonder daily, cause there are always some statements with min_duration > 500ms.

**Comment by darold** [comment]
In incremental mode pgbadger count the number of queries parsed from the last date stored in the LAST_PARSE file. If you have 0 query reported is this because there is no new queries in the log since the last run. The query are all LOG level entries with a duration.
