### ISSUE TITLE
pgbadger > 7.x does not read any query from my postgres log file

### ISSUE THREAD

**Issue by alienpenguin** [dalibo/pgbadger#333]
I use a log_line_prefix like this: '%t %a %u %h ' on postgres 9.5.5
but no pgbadger version > 7.3 is able to identify any query.
The way i call pgbadger (7,8 and 9) is the following: pgbadger -j4 -p '%t %a %u %h ' test.log.txt -o myout.html

i attached a tail of my real log file.
[test.log.txt](https://github.com/dalibo/pgbadger/files/774299/test.log.txt)

**Comment by darold** [comment]
Hi,

Sorry for the response delay, I don't know why but I was not notified of your post. Your log are not well parsed by pgBadger because you need to log the pid of the process in the file. Please look at documentation about the minimum log_line_prefix to use.

Regards,

**Comment by alienpenguin** [comment]
Sorry for the dumb report then... i was trying to figure out what had
changed between 7.x and 8.x+ but did not find the entry in the changelog...
my bad.
Just as a suggestion, pgbadger could report the missing mandatory values in
the log_line_prefix to spot easily silly mistakes like mine.
