### ISSUE TITLE
Incremental mode and CSV

### ISSUE THREAD

**Issue by jgallinari** [dalibo/pgbadger#339]
Hi,

I have one question: why are incremental mode and CSV log file incompatible?

Thanks

**Comment by darold** [comment]
Hi,

They are fully compatible, what make you think that? The only thing that is not possible with cvslog formt is multiprocessing because the Perl Module Text::CSV_XS doen't allow us to seek in the file.

Regards

**Comment by jgallinari** [comment]
Hi,

Actually I would like to use the incremental feature to run pgbadger remotely once an hour and to not start over the parsing every time. But I have the impression the LAST_PARSED information is not taken into consideration. Am I wrong?

Thanks

**Comment by darold** [comment]
In remote mode the entire file is parsed because it is not possible to seek in the file remotely. Line before last run are just skipped but it can take time to reach the last position stored in the LAST_PARSED file following the size of the log.

**Comment by wsdookadr** [comment]
> In remote mode the entire file is parsed because it is not possible to seek in the file remotely. 

According to docs, the `-r` switch runs a `cat` command over a passwordless (presumably key-based) ssh connection. I guess that part doesn't allow the random access.

But random access would be possible if `sshfs` were being use to mount the remote logs [[1]](https://lwn.net/Articles/223867/) [[2]](https://www.admin-magazine.com/HPC/Articles/Sharing-Data-with-SSHFS) with some performance penalty.

**Comment by darold** [comment]
Righ, sshfs will allow random access.
