### ISSUE TITLE
"log_line_prefix" customed does not work with version 9.1 of "pgbadger" 

### ISSUE THREAD

**Issue by pgrepli** [dalibo/pgbadger#340]
Hello,

With the version 9.1 of "pgbadger", we can not custom PostgreSQL log files with "log_line_prefix = 'user=%u,db=%d,time=%t '" using log format 'stderr' or 'syslog'. But this works with the previous version 8.0.

In debug mode, we obtain the following messages:

DEBUG: Unknown line format: user=postgres,db=bench,time=2017-04-11 11:49:12 CEST LOG:  duration: 0.132 ms  statement: UPDATE pgbench_branches SET bbalance = bbalance + 3356 WHERE bid = 1;
DEBUG: Unknown line format: user=postgres,db=bench,time=2017-04-11 11:49:12 CEST LOG:  duration: 0.100 ms  statement: INSERT INTO pgbench_history (tid, bid, aid, delta, mtime) VALUES (1, 1, 1696, 3356, CURRENT_TIMESTAMP);
DEBUG: Unknown line format: user=postgres,db=bench,time=2017-04-11 11:49:12 CEST LOG:  duration: 2.672 ms  statement: END;
DEBUG: Unknown line format: user=,db=,time=2017-04-11 11:49:28 CEST LOG:  automatic analyze of table "bench.public.pgbench_accounts" system usage: CPU 0.01s/0.08u sec elapsed 0.25 sec

Regards

**Comment by darold** [comment]
Hi,

The right log_line_prefix to use is explained in documentation, here is missing the mandatory pid field (%p). After fixing that you will be able to use you custom prefix by using option `-f stderr`.

Regards,

**Comment by pgrepli** [comment]
It works after adding the mandatory field '%p' in "log_line_prefix" parameter.
Thanks
