### ISSUE TITLE
It appears that --prefix does not recognize %n

### ISSUE THREAD

**Issue by ghosthound** [dalibo/pgbadger#343]
Using a log_line_prefix of '%n %p: db=%d,app=%a' results in pgbadger not finding any data.  It appears that build_log_line_prefix_regex() does not include '%n' as a lookup in %regex_map ('%n' is in the map, just doesn't get looked up, see patch below).

This patch should resolve the issue (adds 'n' to the 'audrhptmlscvxie' string):
```index b43cb87..20b67c4 100644
--- a/pgbadger
+++ b/pgbadger
@@ -14056,7 +14056,7 @@ sub build_log_line_prefix_regex
        $llp =~ s/([\[\]\|\(\)\{\}])/\\$1/g;
        $llp =~ s/\%l([^\d])\d+/\%l$1\\d\+/;
        $llp =~ s/\%q//;
-       while ($llp =~ s/(\%[audrhptmlscvxie])/$regex_map{"$1"}->[1]/) {
+       while ($llp =~ s/(\%[audrhpntmlscvxie])/$regex_map{"$1"}->[1]/) {
                push(@param_list, $regex_map{"$1"}->[0]);
        }
        # replace %% by a single %
```

**Comment by darold** [comment]
Right, your patch is applied in commit 56a8349. Thanks.

**Comment by ghosthound** [comment]
excellent, thanks!
