### ISSUE TITLE
Ambiguity in the official documentation?

### ISSUE THREAD

**Issue by andrews812** [dalibo/pgbadger#344]
Hello!
At first, thanks for your great work!
I've just tried to configure postgres for pgbadger 9.1 and found this snippet in the documentation:
 
~~~
Log line prefix could add user, database name, application name and client ip address as follows:

        log_line_prefix = '%t [%p]: [%l-1] user=%u,db=%d,app=%a,client=%h '
~~~

Although, such line does not work for 'stderr' log format!

This snippet is correct:

~~~
Log line prefix for stderr output could also be:

        log_line_prefix = '%t [%p]: [%l-1] db=%d,user=%u,app=%a,client=%h '
~~~

Maybe i misunderstood something, but IMHO it's a kind of ambiguity which cost me some hours of time :(

**Comment by darold** [comment]
Hi Andrew,

Why? For what I can see you have just inverted db and user in the prefix but if I recall well pgBadger doesn't care of any order in this part.

Regards,

**Comment by andrews812** [comment]
Hi,
yes, there're just inverted _db_ and _user_ fields, but in the first format pgBadger 9.1 was unable to recognize log file format:

~~~
FATAL: unable to detect log file format from xxx.log, please use -f option.
~~~

when i used _-f stderr_, he was unable to find any query/event and was generated an empty report

**Comment by darold** [comment]
pgBadger doesn't use the "variable part" of the prefix but just `'%t [%p]: [%l-1] ` to auto detect the log format. pgBadger complain about an unknown format if it can't found enough representative lines to parse in the log file. Maybe this was the reason.

**Comment by andrews812** [comment]
just made a test with a newly created log all went ok. it's strange, but old logs are lost, so issue seems may be closed. i'm sorry for inconvenience!
