### ISSUE TITLE
Change timezone logs

### ISSUE THREAD

**Issue by xdexter** [dalibo/pgbadger#346]
Hello, i'm use my postgres database on AWS (RDS), and isn't possible change "timezone" variable on Postgres, so when i will parse logs with PgBadger my reports are created with date/time wrongs, it's possible configure this value when PgBadger read log files?

OBS: I know that exist the param "--timezone", but this param works only to graphs.

Best

**Comment by julmon** [comment]
Hi,

This PR https://github.com/dalibo/pgbadger/pull/399 intends to implement this feature by adding the new option `--log-timezone`.

Regards,

**Comment by julmon** [comment]
#399 merged
