### ISSUE TITLE
Add Distance to Checkpoints

### ISSUE THREAD

**Issue by jjsantam** [dalibo/pgbadger#348]
The current (9.6) log_checkpoints output comes in the format:

`Jun  7 04:00:03 XXXXXX01 postgres[24069]: [423-1] db=,user=,app=,client= LOG:  checkpoint complete: wrote 0 buffers (0.0%); 0 transaction log file(s) added, 1 removed, 0 recycled; write=0.016 s, sync=0.000 s, total=0.054 s; sync files=0, longest=0.000 s, average=0.000 s; distance=0 kB, estimate=14744 kB

Jun  7 04:29:03 XXXXX01 postgres[24069]: [427-1] db=,user=,app=,client= LOG:  checkpoint complete: wrote 9475 buffers (0.9%); 0 transaction log file(s) added, 0 removed, 0 recycled; write=539.571 s, sync=0.127 s, total=539.796 s; sync files=140, longest=0.050 s, average=0.000 s; distance=174833 kB, estimate=174833 kB`

It is my understanding that the information of 'distance' and 'estimate' is related to the min_wal_size and max_wal_size behaviour, as explained in:

https://www.postgresql.org/message-id/E1YPwGB-0006vL-8V%40gemulon.postgresql.org

Is it possible to add a new graph displaying this two values?

**Comment by darold** [comment]
Thanks for the feature request. Commit b36bdb0 add a new report of checkpoint mean distance/estimate over time.

**Comment by jjsantam** [comment]
Thanks to you for maintaining this cool tool.
