### ISSUE TITLE
Unable to parse .csv file

### ISSUE THREAD

**Issue by Psharm89** [dalibo/pgbadger#350]
Hi All,
I have installed Text::CSV_XS for parsing .csv file but still, I am facing the below issue.

[postgres@abc pgaudit]$ pgbadger -f stderr postgres-2017-07-26_000000.csv  -o abc.html
Can't locate Text/CSV_XS.pm in @INC (@INC contains: /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/ perl5 /usr/share/perl5 .) at /bin/pgbadger line 2620.

cpan[1]> install Text::CSV_XS
Reading '/root/.cpan/Metadata'
  Database was generated on Wed, 26 Jul 2017 09:17:02 GMT
Running install for module 'Text::CSV_XS'
Running make for H/HM/HMBRAND/Text-CSV_XS-1.31.tgz
Fetching with HTTP::Tiny:
http://mirror.liquidtelecom.com/CPAN/authors/id/H/HM/HMBRAND/Text-CSV_XS-1.31.tgz
Fetching with HTTP::Tiny:
http://mirror.liquidtelecom.com/CPAN/authors/id/H/HM/HMBRAND/CHECKSUMS
Checksum for /root/.cpan/sources/authors/id/H/HM/HMBRAND/Text-CSV_XS-1.31.tgz ok
Scanning cache /root/.cpan/build for sizes
............................................................................DONE

  CPAN.pm: Building H/HM/HMBRAND/Text-CSV_XS-1.31.tgz

Checking if your kit is complete...
Looks good
Generating a Unix-style Makefile
Writing Makefile for Text::CSV_XS
Writing MYMETA.yml and MYMETA.json
cp CSV_XS.pm blib/lib/Text/CSV_XS.pm
Running Mkbootstrap for CSV_XS ()
chmod 644 "CSV_XS.bs"
"/usr/bin/perl" -MExtUtils::Command::MM -e 'cp_nonempty' -- CSV_XS.bs blib/arch/auto/Text/CSV_XS/CSV_XS.bs 644
"/usr/bin/perl" "/usr/share/perl5/vendor_perl/ExtUtils/xsubpp"  -typemap '/usr/share/perl5/ExtUtils/typemap'  CSV_XS.xs > CSV_XS.xsc
mv CSV_XS.xsc CSV_XS.c
gcc -c   -D_REENTRANT -D_GNU_SOURCE -fno-strict-aliasing -pipe -fstack-protector -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -O2 -g -pipe -Wall -Wp ,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic   -DVERSION=\"1.31\" -DXS_VERSION=\"1.31 \" -fPIC "-I/usr/lib64/perl5/CORE"   CSV_XS.c
rm -f blib/arch/auto/Text/CSV_XS/CSV_XS.so
gcc  -shared -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -Wl,- z,relro  CSV_XS.o  -o blib/arch/auto/Text/CSV_XS/CSV_XS.so  \
      \

chmod 755 blib/arch/auto/Text/CSV_XS/CSV_XS.so
Manifying 1 pod document
  HMBRAND/Text-CSV_XS-1.31.tgz
  /bin/make -- OK
'YAML' not installed, will not store persistent state
Running make test
"/usr/bin/perl" -MExtUtils::Command::MM -e 'cp_nonempty' -- CSV_XS.bs blib/arch/auto/Text/CSV_XS/CSV_XS.bs 644
PERL_DL_NONLAZY=1 "/usr/bin/perl" "-MExtUtils::Command::MM" "-MTest::Harness" "-e" "undef *Test::Harness::Switches; test_harness(0, 'blib/lib', 'blib/arch')" t/*.t
t/00_pod.t ........ skipped: Test::Pod 1.00 required for testing POD
t/01_pod.t ........ skipped: Test::Pod::Coverage required for testing POD Coverage
t/10_base.t ....... ok
t/12_acc.t ........ ok
t/15_flags.t ...... ok
t/20_file.t ....... ok
t/21_lexicalio.t .. ok
t/22_scalario.t ... ok
t/30_types.t ...... ok
t/40_misc.t ....... ok
t/41_null.t ....... ok
t/45_eol.t ........ ok
t/46_eol_si.t ..... ok
t/50_utf8.t ....... ok
t/51_utf8.t ....... ok
t/55_combi.t ...... ok
t/60_samples.t .... ok
t/65_allow.t ...... ok
t/70_rt.t ......... ok
t/75_hashref.t .... ok
t/76_magic.t ...... ok
t/77_getall.t ..... ok
t/78_fragment.t ... ok
t/79_callbacks.t .. ok
t/80_diag.t ....... ok
t/81_subclass.t ... ok
t/85_util.t ....... ok
t/90_csv.t ........ ok
t/91_csv_cb.t ..... ok
All tests successful.
Files=29, Tests=50834, 45 wallclock secs ( 4.18 usr  0.16 sys + 43.91 cusr  0.69 csys = 48.94 CPU)
Result: PASS
  HMBRAND/Text-CSV_XS-1.31.tgz
  /bin/make test -- OK
Running make install
"/usr/bin/perl" -MExtUtils::Command::MM -e 'cp_nonempty' -- CSV_XS.bs blib/arch/auto/Text/CSV_XS/CSV_XS.bs 644
Manifying 1 pod document
Files found in blib/arch: installing files in blib/lib into architecture dependent library tree
Installing /root/perl5/lib/perl5/x86_64-linux-thread-multi/auto/Text/CSV_XS/CSV_XS.so
Installing /root/perl5/lib/perl5/x86_64-linux-thread-multi/Text/CSV_XS.pm
Installing /root/perl5/man/man3/Text::CSV_XS.3pm
Appending installation info to /root/perl5/lib/perl5/x86_64-linux-thread-multi/perllocal.pod
  HMBRAND/Text-CSV_XS-1.31.tgz
  /bin/make install  -- OK

cpan[2]> quit
Terminal does not support GetHistory.
Lockfile removed.
[root@abc:/home/psharm89]#
#-> rpm -qa | grep perl-CPAN
perl-CPAN-1.9800-286.el7.noarch

**Comment by darold** [comment]
cpan seems to have installed the module into /root/perl5/lib/perl5/x86_64-linux-thread-multi/ ,  does your perl binary knows about this path? Look ar the result of the perl -V command and especially the @INC variable. The module must be installed in on of these paths or add /root/perl5/lib/perl5/x86_64-linux-thread-multi/ to the @INC variable.

**Comment by Psharm89** [comment]
Hi,
now it's working.
I have installed Text:: CSV_XS using PostgreSQL user.

[postgres@abcpgaudit]$  perl -MCPAN -e shell

cpan> install Text::CSV_XS

**Comment by Psharm89** [comment]
Please share commant how to Perform continuous log analysis (incremental mode) in the same HTML file.

**Comment by darold** [comment]
you can not perform incremental mode on the same HTML file, you will one HTML file per day and one per week. For example the following cron entry:
```
0 4 * * * /usr/bin/pgbadger -I -q /var/log/postgresql/postgresql.log.1 -O /var/www/pg_reports/
```
will continuously generate an HTML report per day and week each day at 4 am after log has been rotated by log_rotate.

If you have small log files you can update the report each hours:
```
0 */1 * * * /usr/bin/pgbadger -I -q /var/log/postgresql/postgresql.* -O /var/www/pg_reports/
```
Here it will parse all postgresql.* file each hours and rebuild latest HTML reports. Log files that have already been parsed will not be parsed twice even after a cycle of log_rotate, same, completed report of past days or weeks will not be generated again.

See README file or `man pgbadger` to have more information.
