### ISSUE TITLE
Use of uninitialized value $last in uc at line 14401

### ISSUE THREAD

**Issue by johnkrugger** [dalibo/pgbadger#353]
Hi, 

Have had the following error when processing logs:
Use of uninitialized value $last in uc at /root/cron/pgbadger line 14401

The query that is at fault is:
`(    SELECT        COALESCE (count (d.id), 0) dc,        d.state,        d.stateresult    
FROM        table1 d    
WHERE        d.mi_id = 19130        AND d.active    
GROUP BY        d.state,        d.stateresult); `

Seems the parenthesis around the query cause a problem for the processing of the logs.

**Comment by jpargudo** [comment]
Dear @johnkrugger can you test my trivial patch?
Does this one solves your issue?
Thanks,

**Comment by johnkrugger** [comment]
Reprocessed a log file that was outputting the error and with your patch it worked flawlessly.

Problem solved.
