### ISSUE TITLE
Only data in events, query always empty

### ISSUE THREAD

**Issue by ch-bas** [dalibo/pgbadger#354]
Hi everybody,
I'm using pgbadger with PostgreSQL  and i'm facing a problem like the described in the [issue 345](https://github.com/dalibo/pgbadger/issues/345) .
I tried to use lc_messages to C but always the same result.

My log looks like this:
2016-06-19 01:55:40 CEST STATEMENT:  ALTER FUNCTION public.....
my log_line_prefix = '%t %i'
the result after running pgbadger:
Parsed 237314 bytes of 237314 bytes, queries: 0, events: 908

any help please?

**Comment by darold** [comment]
Hi,

There is a README file in the source tree or a call to `man pgbadger` on your box that might help you to find the answer to your issue.

Regards,

**Comment by ch-bas** [comment]
thx, after running pgbadger with the full path: /var/lib/pgsql/pgbadger-9.1/pgbadger with another log file , the problem was resolved.
