### ISSUE TITLE
gzip: stdout: Broken pipe

### ISSUE THREAD

**Issue by DeyualSimu** [dalibo/pgbadger#356]
First: sorry for my english, and i don't know if this will be here. but...

I using python to call pgbadger with the next command:

```python
command = ' '.join(['pgbadger -f stderr -p \'%t [%p]: [%l-1] user=%u,db=%d,client=%h \'','-o %s.bin' % (date),'-O',directory,'%s%s' % (LOCAL_PATH,FILE_NAME)])
log(os.system(command))
```

This generate a file with "NO DATASET".
and the log is:
```bash
gzip: stdout: Broken pipe
[========================>] Parsed 22523358 bytes of 22523358 (100.00%), queries: 0, events: 0
LOG: Ok, generating binary report...
```

I don't know what is my error, since there is no problem with generate the report manually.

**Comment by bersace** [comment]
Hi @DeyualSimu, thanks for the report.

It looks like pgbadger is not very nice with gzip. Can you isolate the case without Python ? Just the call to pgbadger in a terminal that trigger this error.

Thanks !

**Comment by bersace** [comment]
@DeyualSimu Can you tell me how you solved the issue ? Thanks !
