### ISSUE TITLE
Tempfile for canceled queries attributed to last successful query.

### ISSUE THREAD

**Issue by kkartaltepe** [dalibo/pgbadger#358]
Had a query that generated some tempfiles but the was subsequently canceled before it completed. These tempfiles were then attributed to the last successful query in that session which was quite confusing (since the last query was quite innocuous).

Let me know if you need a sample log file if you cannot produce on your own.

Issue was on: pgBadger version 9.2

**Comment by ng-pe** [comment]
Hi,
Yes, you can attach the log sample. it will make it easier and faster to understand the problem.
Regards,

**Comment by kkartaltepe** [comment]
Sorry i no longer have the example log file anymore. I will work on trying to reproduce a log file but if im not misremembering it should come up with an example workflow like this.
```
Start 2 psql sessions, A and B. Issue the following commands
A) select count(*) from generate_series(0, 10000) as A cross join A; -- append self joins/order by's as needed to spill to disk.
-- While session A is working
B) select 1+1;
A) -- Cancel the session with ctrl-c
```
This should replicate what i was seeing and the tempfile associated with session A will be attributed to the sql run in session B.
