### ISSUE TITLE
--exclude-query don't work when the input-file is a binary.

### ISSUE THREAD

**Issue by DeyualSimu** [dalibo/pgbadger#359]
i have problem to exclude querys.
i use 
```@bash
$PGBAGDER -f stderr --exclude-query "^(VACUUM)*" -o $OUT.html $IN.bin
```
 
- pgbadger versión 9.2 

i add in DEBUG mode, the line : `&logmsg('DEBUG',$pattern);`
to the sub check_regex (line 1994)
and it is reading the regexp, but don't filter that.

Update 08-Sep-2017:
I read the source code and i noticed that when is a binary file it don't call the function that exclude querys.

_Enviado desde mi Redmi Note 4 usando [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by bersace** [comment]
Hi @DeyualSimu Thanks for the report ! I'm looking at this !

**Comment by bersace** [comment]
@DeyualSimu actually, the binary format is a **report** format, not a **log** format. `--exclude-query` applies to log analysis, not report output.

Once you have binary reports, you can only output them as HTML, JSON, etc. or combine it with other reports. But not remove stats from the report.

You must exclude `VACUUM` when generating `binary` reports.

**Comment by bersace** [comment]
Let's close this. Please reopen if you have further question on the topic !
