### ISSUE TITLE
Can't run multiple instances of pgbadger without setting TMPDIR

### ISSUE THREAD

**Issue by dtseiler** [dalibo/pgbadger#367]
If I want to run multiple instances of pgbadger, I need to set the TMPDIR environment variable uniquely for each session, otherwise all but the first instance will see that first instance's pgbadger.pid file and abort.

Could we set something unique for PID_DIR that would allow us to run pgbadger multiple times concurrently without the extra step?

**Comment by bersace** [comment]
Hi @dtseiler thanks for pointing this. That's a good idea.

**Comment by bersace** [comment]
@dtseiler did you see `--pid-dir` ?

**Comment by dtseiler** [comment]
Ahhh no I missed that item. I see it now in the man page. That's my bad.

**Comment by dtseiler** [comment]
Just testing that feature out. One small issue is that pgbadger doesn't create the PID_DIR if it doesn't already exist. So then it fails with:

```
$ pgbadger -I postgresql-2017-09-19_140658.log -O pgbadger_reports/foo --pid-dir /tmp/pgbadger-foo
FATAL: can't create pid file /tmp/pgbadger-foo/pgbadger.pid, No such file or directory
```
