### ISSUE TITLE
Missing graph INSERT/UPDATE/DELETE Traffic

### ISSUE THREAD

**Issue by julianopg** [dalibo/pgbadger#373]
Hi guys

There is no one information on the graph I**NSERT/UPDATE/DELETE Traffic,** the other graphs are ok and I can see the "Write Queries" on "General Activity", can someone help me, please?

More Info:
Ubuntu version 16.04
Pgbadger version 9.2-1

Executable command:
pgbadger -I -q /var/log/postgresql/postgresql-9.6-main.log -O /mydir/

Postgres version 9.6

Postgres config:
log_min_duration_statement = 5s
log_statement = all
log_min_error_statement  = error

Thanks in advance 😄

**Comment by pgiraud** [comment]
This chart actually shows the average for "number of queries per second" for a 5 minutes period.
Currently the values are converted to integer (rounded). In your case, you most probably don't have enough traffic which means that average si below 0.5 queries/s.
What we could do is get rid of the integer conversion. Other option would be to show the "maximum" (peak for a 5 min period) instead of the "average".
Finally, the chart title should read "(MAX) WRITE QUERIES PER SECOND (5 MINUTES PERIOD)".

**Comment by julianopg** [comment]
Hi pgiraud

I guess I have enough queries because the yesterday's report shows me thousands of write queries, please find the attached image:
![screen shot 2017-10-05 at 13 28 09](https://user-images.githubusercontent.com/30405784/31227395-96afac08-a9d1-11e7-93a4-18f2886f48c0.png)

Any suggestions?

**Comment by julianopg** [comment]
Hi pgiraud

Thanks for your comment.

I have looked into the general activity and realized that with thousand of queries takes 0ms of average duration, so it can't be correct.

Most of my write queries are inserts auto executed on jobs steps by pgagent and using temp tables so, is it incompatible for count the average time?

Should I change the log_min_duration_statement=5s to log_min_duration_statement=0?

Please find the attached image for more information:
![screen shot 2017-10-05 at 13 28 09](https://user-images.githubusercontent.com/30405784/31227914-77a6c236-a9d3-11e7-81f8-5beb678ea8b5.png)

**Comment by pgiraud** [comment]
I'm not surprised that you don't see anything in the `write queries` chart since 173 request per hour is less than 0.05 per second. Which is converted automatically to '0'.

The 0ms is indeed a bit weird but it has no influence on the chart.

What does the `Queries` tab in `Global Stats` and `General Activity` sections look like ?
Can you also check that duration is correctly set in the log file for each query?

**Comment by julianopg** [comment]
Hi

The `Queries` look like this:

![screen shot 2017-10-05 at 15 42 19](https://user-images.githubusercontent.com/30405784/31233479-ab5faea6-a9e4-11e7-9919-6019e096d36f.png)


![screen shot 2017-10-05 at 15 42 33](https://user-images.githubusercontent.com/30405784/31233481-adcf1b68-a9e4-11e7-8074-75f906b69dd1.png)



How can I check the duration configured to the log file for each query? Is it any of the below configuration?
```

            name             |                     setting                     
-----------------------------+-------------------------------------------------
 log_autovacuum_min_duration | 0
 log_checkpoints             | on
 log_connections             | on
 log_destination             | stderr
 log_directory               | pg_log
 log_disconnections          | on
 log_duration                | on
 log_error_verbosity         | default
 log_executor_stats          | off
 log_file_mode               | 0600
 log_filename                | postgresql-%Y-%m-%d_%H%M%S.log
 log_hostname                | off
 log_line_prefix             | %t [%p]: [%l-1] user=%u,db=%d,app=%a,client=%h 
 log_lock_waits              | on
 log_min_duration_statement  | 5s
 log_min_error_statement     | error
 log_min_messages            | warning
 log_parser_stats            | off
 log_planner_stats           | off
 log_replication_commands    | off
 log_rotation_age            | 1
 log_rotation_size           | 10240
 log_statement               | all
 log_statement_stats         | off
 log_temp_files              | 0
 log_timezone                | UTC
 log_truncate_on_rotation    | off
 logging_collector           | off
 syslog_facility             | local0
 syslog_ident                | postgres
 syslog_sequence_numbers     | on
 syslog_split_messages       | on
 wal_log_hints               | off
```

**Comment by pgiraud** [comment]
@julianopg can you open the log file in an editor and check if you have a duration set for a log line related to an write query (insert for example)?

**Comment by julianopg** [comment]
Hi pgiraud

As my inserts are executed by jobs all the inserts entries found on the Postgres log are similar to below:

2```
017-10-06 14:43:35 UTC [20210]: [6133-1] user=pgagent,db=postgres,app=pgAdmin 4 - DB:postgres,client=10.0.0.1 LOG:  statement: SELECT
	   (SELECT sum(tup_inserted) FROM pg_stat_database WHERE datname = (SELECT datname FROM pg_database WHERE oid = 0123)) AS "Inserts",
	   (SELECT sum(tup_updated) FROM pg_stat_database WHERE datname = (SELECT datname FROM pg_database WHERE oid = 0123)) AS "Updates",
	   (SELECT sum(tup_deleted) FROM pg_stat_database WHERE datname = (SELECT datname FROM pg_database WHERE oid = 0123)) AS "Deletes"
```

`2017-10-06 14:47:16 UTC [2439]: [4691-1] user=pgagent,db=postgres,app=[unknown],client=127.0.0.1 LOG:  statement: SELECT J.jobid   FROM pgagent.pga_job J  WHERE jobenabled    AND jobagentid IS NULL    AND jobnextrun <= now()    AND (jobhostagent = '' OR jobhostagent = 'my_server_name') ORDER BY jobnextrun`

So, I did this manually insert on pgadmin instead of use pgagent ```
INSERT INTO temp.test(
	id, inserted)
	VALUES (1, 'test');
``` 

And I get this on the log:

```
2017-10-06 15:00:14 UTC [5882]: [12-1] user=julianopg,db=postgres,app=pgAdmin 4 - CONN:6789592,client=10.0.0.1 LOG:  statement: INSERT INTO temp.test(
2017-10-06 15:00:14 UTC [5882]: [14-1] user=julianopg,db=postgres,app=pgAdmin 4 - CONN:6789592,client=10.0.0.1  STATEMENT:  INSERT INTO temp.test(
```

**Comment by julianopg** [comment]
Hi

Is it possible that using functions, the INSERT statement is obfuscated enough that pgbagdger won't recognize it?

Source (pgpool):
https://books.google.com/books?id=AVQoDwAAQBAJ&lpg=PA99&pg=PA132#v=onepage&q&f=false

**Comment by julmon** [comment]
Hi @julianopg 

You're right, INSERT/UPDATE/DELETE statements triggered inside functions won't be seen as write queries by pgBadger because Postgres logs only shows `SELECT ... myfunction(...)`, then pgBadger can't have any clue about what `myfunction()` did.

Can we close this case ?

Thanks,
