### ISSUE TITLE
Total and details per client are different for "Query per application"

### ISSUE THREAD

**Issue by rboxeur** [dalibo/pgbadger#374]
Hi 
We are currently using pgbadger to collect metrics for our own PostgreSQL databases.
When we get into details by clicking on "Query per application" for example for the green one
![issue_query_per_application](https://user-images.githubusercontent.com/10597062/31221779-1a639d50-a9c5-11e7-8d8d-a135af9e9ca9.PNG)

we noticed that Total and details are different (48 millions compared to almos 37 millions) (see below)

![pgbadger_issue](https://user-images.githubusercontent.com/10597062/31221884-6b2eedd4-a9c5-11e7-84d9-12c285a97508.png)

Is it a bug or did I set up pgbadger the wrong way?

Below are parameters taken from postgresql.conf

listen_addresses = '*'
port = 5432                             # (change requires restart)
max_connections = 750                   # (change requires restart)
authentication_timeout = 10             # 1s-600s
shared_buffers=30GB
work_mem = 128MB
maintenance_work_mem = 6GB              # min 1MB
shared_preload_libraries = '$libdir/dbms_pipe,$libdir/edb_gen,$libdir/plugins/plugin_debugger,$libdir/plugins/plugin_spl_debugger,$libdir/sql-profiler'
bgwriter_lru_maxpages = 100             # 0-1000 max buffers written/round
wal_level = hot_standby                 # minimal, archive, or hot_standby
wal_buffers = 32MB
checkpoint_segments =  560              # in logfile segments, min 1, 16MB each
checkpoint_timeout = 10min              # range 30s-1h
checkpoint_completion_target = 0.9      # checkpoint target duration, 0.0 - 1.0
checkpoint_warning = 585                # 0 disables
archive_mode = off              # allows archiving to be done
archive_command = 'cp -i %p /netapp/Stream/%f && chmod 777 /netapp/Stream/%f'   # command to use to archive a logfile segment
archive_timeout = 1200          # force a logfile segment switch after this
max_wal_senders = 10
wal_keep_segments = 360         # in logfile segments, 16MB each; 0 disables
vacuum_defer_cleanup_age = 10000
synchronous_standby_names = ''
hot_standby = on                        # "on" allows queries during recovery
max_standby_archive_delay = 600s
max_standby_streaming_delay = 600s
hot_standby_feedback = on               # send info from standby to prevent
enable_bitmapscan = off
enable_nestloop = off
random_page_cost = 0.1                  # same scale as above
effective_cache_size = 24GB
default_statistics_target = 2000
log_destination = 'stderr'              # Valid values are combinations of
logging_collector = on          # Enable capturing of stderr and csvlog
log_directory = 'pg_log'
log_filename = 'enterprisedb-%Y-%m-%d_%H%M%S.log'       # log file name pattern,
log_file_mode = 0600                    # creation mode for log files,
log_truncate_on_rotation = off          # If on, an existing log file with the
log_rotation_age = 1d                   # Automatic rotation of logfiles will
log_rotation_size = 100MB               # Automatic rotation of logfiles will
log_min_duration_statement = 0  # -1 is disabled, 0 logs all statements
log_checkpoints = on
log_connections = on
log_disconnections = on
log_duration = on
log_hostname = on
log_line_prefix = '%t [%p]: [%l-1] user=%u,db=%d,app=%a,client=%h '
log_lock_waits = on                     # log lock waits >= deadlock_timeout
log_statement = 'all'                   # none, ddl, mod, all
log_temp_files = 0                      # log temporary files equal or larger
autovacuum = on                 # Enable autovacuum subprocess?  'on'
log_autovacuum_min_duration = 0 # -1 disables, 0 logs all actions and
datestyle = 'redwood,show_time'
lc_messages = 'en_US.UTF-8'                     # locale for system error message
lc_monetary = 'en_US.UTF-8'                     # locale for monetary formatting
lc_numeric = 'en_US.UTF-8'                      # locale for number formatting
lc_time = 'en_US.UTF-8'                         # locale for time formatting
default_text_search_config = 'pg_catalog.english'
deadlock_timeout = 1s
max_locks_per_transaction = 512

**Comment by julmon** [comment]
Hi,

I think I'm reproducing this issue with logs coming from a pgbench run, overall number of queries seems totally wrong:
```console
$ grep 'statement: ' ~/tmp/postgresql-10-main.log | wc -l
2052394
```

From the report:
![pgbadger-374](https://user-images.githubusercontent.com/920753/41316872-d87db2e2-6e93-11e8-84c9-c1622e0215c6.png)
