### ISSUE TITLE
pgbadger no dataset 

### ISSUE THREAD

**Issue by zoubayer** [dalibo/pgbadger#376]
Hi everyone,
after configuring pgbadger i only have events tab that is working. when clicking on other tabs like sessions, queries... all of them are empty " no dataset".

**Comment by j0hannes** [comment]
It doesn't say so in the changelog, but maybe the log output changed in pg10 and pgbadger's patterns do not match anymore?

**Comment by zoubayer** [comment]
i am using pg 9.6

**Comment by j0hannes** [comment]
For me, the prefix was wrong (I took it from the manual). Did you specify the prefix you use in your postgresql.conf?

**Comment by zoubayer** [comment]
you meant this one : 
log_line_prefix = '%t [%p]: [%l-1]'

**Comment by j0hannes** [comment]
Yes, did you try calling pgbadger with `--prefix='%t [%p]: [%l-1]'`?

**Comment by zoubayer** [comment]
i changed the postgresql log  with pgbouncer log and everything is working good. the problem so was that postgresql log file is not configured to englob all the events ( that's what's i had as a conclusion, i am a begginer )

**Comment by pgiraud** [comment]
@zoubayer can we close the current issue?
