### ISSUE TITLE
Out of memory issue

### ISSUE THREAD

**Issue by gandrei95** [dalibo/pgbadger#377]
Hello guys,

I've tried recently parsing some csv logs with pgbadger (that have worked previously fine), and it throws me "**Out of memory!**" after an amount of time without doing pretty much anything. I must mention the fact that I have done some cleaning in .csv logs, but in my opinion I really do not think this is the problem.

If it helps on something here is the command I use for parsing the logs took via ssh connection(which is established and i guarantee that).

`/usr/local/bin/pgbadger -r pgsql_server_ip --ssh-user root -f csv -I -q /var/lib/pgsql/9.6/data/pg_log/postgresql-*.csv -O /home/www-data/pgbadger/pgsql_server_ip/postgresql`

I also use this command for a couple of pgsql servers and works perfectly.

**Comment by julmon** [comment]
Hi @gandrei95 

Thanks for the report. This is a known issue, to process large amount of data, pgbadger needs lot of memory.

**Comment by darold** [comment]
The problem here is more related to the CSV parser, if you have edited the log you probably have broken the CSV formal and the CSV parser is loading all in memory. I think this issue can be closed, this looks to be a misused.
