### ISSUE TITLE
FATAL: unable to detect log file format

### ISSUE THREAD

**Issue by tapanshah7891** [dalibo/pgbadger#378]
Hello,

I am facing issue with postgres log processing. My postgres create log file in UTF8 & ASCII format.
When pgbadger process ACSII format logs it works well but I face issue with processing UTF8 format logs.

Can you please suggest how can I process UTF8 format logs.

FYI:
root@db1:~ # pgbadger -J 4 -I /usr/local/pgsql/data/pg_log/postgresql-2017-11* -O /pgbadger
FATAL: unable to detect log file format from /usr/local/pgsql/data/pg_log/postgresql-2017-11-01_132008.log, please use -f option.
 
root@db1:~ # file /usr/local/pgsql/data/pg_log/postgresql-2017-11-01_132008.log
/usr/local/pgsql/data/pg_log/postgresql-2017-11-01_132008.log: UTF-8 Unicode text, with very long lines
 
Whereas some file are of ASCII text and it process well:
root@db1:~ # file /usr/local/pgsql/data/pg_log/postgresql-2017-11-01_181718.log
/usr/local/pgsql/data/pg_log/postgresql-2017-11-01_181718.log: ASCII text, with very long lines

**Comment by bourcier92** [comment]
Hello,
Having the same problem.
Tested on PostgreSQL 9.5 with pgbadger 9.2.
echo /var/log/postgresql/postgresql-9.5-bofi01.log | \
> perl /home/postgres/tools/pgbadger-9.2 - -q --prefix "%t %u %d %r %p %i %e %c %l " \
> --outfile /tmp/PostgreSQL_Report_bofi01.html --extension html
FATAL: unable to detect log file format from -, please use -f option.

grep prefix /etc/postgresql/9.5/bofi01/postgresql.conf
log_line_prefix = '%t %u %d %r %p %i %e %c %l '                 # special values:

I tried many solutions (suppress long lines / make queries on one line, added -f stderr option).
No solution is working.

**Comment by bourcier92** [comment]
Hello,
I managed to solve my problem. 
Replacing "echo /var/log/postgresql/postgresql-9.5-bofi01.log" by "cat /var/log/postgresql/postgresql-9.5-bofi01.log" was the solution.

**Comment by julmon** [comment]
Hi @tapanshah7891 

Could you send me one of your UTF8 log file at julmon at gmail dot com ?

**Comment by bourcier92** [comment]
HelloThe problem is solved.I made a mistake by submiting the log file name instead of the content of the log file.I added a comment in Git for that.
Thank you.Regards.

    Le mercredi 13 juin 2018 à 13:16:26 UTC+2, Julien Tachoires <notifications@github.com> a écrit :  
 
 
Hi @tapanshah7891

Could you send me one of your UTF8 log file at julmon at gmail dot com ?
