### ISSUE TITLE
JSON output missing some information

### ISSUE THREAD

**Issue by reuben453** [dalibo/pgbadger#379]
The JSON output format from pgbadger is missing some information that is present in the html output.

Specifically, "Time Consuming queries (N)", "Most Frequent Queries (N)" and "Normalized Slowest Queries" are not present in the JSON output but they are present in the html output.

Can these 3 keys also be added to the json ouput?

**Comment by aocenas** [comment]
Hi @reuben453 , not 100% sure but I think this is computed from `normalyzed_info` key in the json, as it seems there is all the data needed to compute those stats.
