### ISSUE TITLE
incompatibilities when moving from pgFouine to pgBadger

### ISSUE THREAD

**Issue by SaanSingh** [dalibo/pgbadger#386]
Hello I was using pgfouine and now moved to pgBadger, in the html file I see some issue regarding "Total query duration".

It is taking twice the time in pgBadger then pgFouine.

Any idea?

**Comment by daamien** [comment]
Hi ! 

Thanks for this message report !  For the record, pgfouine is obsolete. The last vesion was published in 2010.

Can provide the log file you analyzed, the commande line you used with pgBadger and the pgfouine report ?

**Comment by SaanSingh** [comment]
Thanks for the response.

That's why we are moving to pgBadger.

Can you please provide me your email id to send the details only to you. As I really don't want to share the log and reports here 

Thanks

**Comment by SaanSingh** [comment]
Hi,
I could see that pgbadger is having more SELECT statements than pgfouine. Although Number of select statements are same in both.

Is is correct to say that pgfouine don't list all the statements and pgbadger does and because of that there is much difference between Total time?

**Comment by darold** [comment]
Yes this is correct provided that you does not have enabled log_statement and log_min_duration_statement at the same time in your postgresql.conf.
