### ISSUE TITLE
PgBadger9.2: General activity table missing rows 

### ISSUE THREAD

**Issue by tadsko** [dalibo/pgbadger#389]
Hello Guys, 

Does anyone know what is wrong with this table? There were missing row from 16-23 hours. 

![image](https://user-images.githubusercontent.com/35524033/35035493-8490363c-fbac-11e7-93f5-9870bfcf8721.png)

I already done google search but there are no related topics to justify this one. I hope you could help me. Thanks

**Comment by DeyualSimu** [comment]
I usually happen when there are no logs associated with these hours, so, the pgbadger assumes that the log is only between the hours recorded: 0-15.

**Comment by tadsko** [comment]
You're right @DeyualSimu . Thank you! I set the scheduler to perform pgbadger on yesterday's log and was able to view the missing hours.
