### ISSUE TITLE
Documented --Jobs option is ignored 

### ISSUE THREAD

**Issue by chad-iris** [dalibo/pgbadger#391]
From https://dalibo.github.io/pgbadger/ (and similarly in --help message):

>     -J | --Jobs number     : number of log file to parse in parallel. Default
>                              is 1, run as single process.

But the code is (v9.2 line 422):
>         "J|job_per_file=i"         => \$job_per_file,

Suggestion: either make --Jobs work or change documentation to be --jobs_per_file option.

**Comment by bersace** [comment]
@chad-iris thanks for reporting it. I changed pgbadger to match documentation rather than change documentation everywhere.
