### ISSUE TITLE
NO DATASET with testing purpose

### ISSUE THREAD

**Issue by lres7399** [dalibo/pgbadger#397]
Hello,
My postgresql version is 9.6.3  on Redhat 7
pgBadger version 9.2

I activated  some logging in postgresql.conf
These are settings

log_min_duration_statement=0
 log_checkpoints = on
        log_connections = on
        log_disconnections = on
        log_lock_waits = on
        log_temp_files = 0
        log_autovacuum_min_duration = 0
        log_error_verbosity = default
log_line_prefix= '%t [%p]: [%l-1] '
set lc_messages='C'
 
I restart  the DB.
I generated  some datas with  pgbench.

When I run pgbadger : pgbadger -f stderr -v -d tst pg_log/postgresql-*.log -o pg_log/pgebch.html
I get NO DATASET and the message Unkown line format

DEBUG: Unknown line format: < 2018-03-14 09:08:38.505 CET > LOG:  duration: 0.102 ms  statement: SELECT abalance FROM pgbench_accounts WHERE aid = 63067;
DEBUG: Unknown line format: < 2018-03-14 09:08:38.505 CET > LOG:  duration: 0.210 ms  statement: UPDATE pgbench_accounts SET abalance = abalance + -3488 WHERE aid = 3333350;
DEBUG: Unknown line format: < 2018-03-14 09:08:38.505 CET > LOG:  duration: 0.210 ms  statement: UPDATE pgbench_accounts SET abalance = abalance + 3208 WHERE aid = 1259451;
DEBUG: Unknown line format: < 2018-03-14 09:08:38.505 CET > LOG:  duration: 0.229 ms  statement: UPDATE pgbench_accounts SET abalance = abalance + -2863 WHERE aid = 63658;
DEBUG: Unknown line format: < 2018-03-14 09:08:38.505 CET > LOG:  duration: 0.117 ms  statement: UPDATE pgbench_tellers SET tbalance = tbalance + 4491 WHERE tid = 182;
DEBUG: Unknown line format: < 2018-03-14 09:08:38.505 CET > LOG:  duration: 0.120 ms  statement: UPDATE pgbench_tellers SET tbalance = tbalance + -3468 WHERE tid = 66;
DEBUG: Unknown line format: < 2018-03-14 09:08:38.505 CET > LOG:  duration: 0.083 ms  statement: INSERT INTO pgbench_history (tid, bid, aid, delta, mtime) VALUES (163, 37

I guess there is problem with  log_line_prefix .

What's wrong here please ?

Rgds,

**Comment by lres7399** [comment]
Hi, 
I found the problem : I had to add --prefix and change  log_line_prefix to '%m [%p]: [%l-1] '

**Comment by bersace** [comment]
@lres7399 nice. Let's close the issue.
