### ISSUE TITLE
Checkpoint lines not processed in some cases

### ISSUE THREAD

**Issue by manthos** [dalibo/pgbadger#398]
There are many checkpoint lines on log and they are in accordance to pgbadger query format e.g.

`2018-03-18 03:40:02 EDT [10043-26] LOG:  checkpoint complete: wrote 705 buffers (1.1%); 0 transaction log file(s) added, 0 removed, 0 recycled; write=70.332 s, sync=0.004 s, total=70.338 s; sync files=4, longest=0.004 s, average=0.001 s; distance=4243 kB, estimate=7253 kB`

But they are not processed by pgbadger command (and 0/NO DATA shown in report)

`pgbadger --prefix '%t [%p-%l] %q%u@%d ' postgres.log`

when postgres.log is created with postgresql.conf also `log_line_prefix = '%t [%p-%l] %q%u@%d '  `

Might be related to a workaround proposed for "%q in log_line_prefix not handled correctly #272" 

This postgresql version PostgreSQL 9.5.12, pgbadger 7.1

**Comment by darold** [comment]
PR #396 has fixed this issue
