### ISSUE TITLE
Request to add hostname on the top of the pgbadger report

### ISSUE THREAD

**Issue by Psharm89** [dalibo/pgbadger#406]
Hello Dalibo,

I am facing one issue actually i have 1000 of PostgreSQL database server and its very difficult to find out which report is for which particular  PostgreSQL database server, So Is it possible to add HOSTNAME on the top of the report, show it will clear this particular report is for this particular database server.
Its very help for us.

Thanks in advance..!!!!

-Pawan

**Comment by Psharm89** [comment]
Thanks..its done for me..i have created one shell script which will modified the index.html file and added hostname on the top.

-Pawan

**Comment by darold** [comment]
Hi,

Why not use the `-T "your title" option? For example:
```
pgbadger -T "PostgreSQL Log Report for $HIOSTNAME" /var/log/postgresql/postgresql.log
```
Regards,
