### ISSUE TITLE
Use --pid-dir instead of --pid-file in README

### ISSUE THREAD

**Issue by Guysbert** [dalibo/pgbadger#428]
Your readme still says --pid-file while pgbadger only understands --pid-dir. Please change that. Thank you :-)

Great software btw.

**Comment by pgiraud** [comment]
As far as I know, the current option is actually `--pid-file`.
See https://github.com/dalibo/pgbadger/commit/7358f41d6977b89459a7b98a0fc70baffc279dba

This means that the README is up-to-date.

**Comment by Guysbert** [comment]
Strange.
It says I am up to date:
```bash
$ pgbadger --version
pgBadger version 9.2`
```

But when I try to run the help command ist says:
```bash
$ pgbadger --help | grep "\-\-pid"
    --pid-dir dirpath      : set the path of the directory where the pid file
```

**Comment by pgiraud** [comment]
9.2 is the latest stable version
Unfortunately no new version has been released since the commit quoted above.
The README in github matches the very last version of the code.
Closing.
