### ISSUE TITLE
No execution plan with query when auto_explain enable

### ISSUE THREAD

**Issue by bcarriere** [dalibo/pgbadger#71]
With pgfouine when we load the shared_preload_libraries auto_explain. the report generated with pgfouine give the plan with the request found in log.
It is not implemented with pgbadger.
Was it a bug in pgfouine ?
Are you going to reproduce this fonctionality with pgbadger or not ?

**Comment by darold** [comment]
Latest commits add this feature, auto_explain explain plans are shown in-line with top queries when available. If you click on the Explain plan label the plan will be automatically loaded on explain.depesz.com

Regards,
